// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remoteCallService.proto

package com.ops.sc.rpc.grpc;

public interface RemoteCallRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RemoteCallRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.RpcCallBackResponse rpcCallBackResponse = 1;</code>
   */
  boolean hasRpcCallBackResponse();
  /**
   * <code>.RpcCallBackResponse rpcCallBackResponse = 1;</code>
   */
  com.ops.sc.rpc.grpc.callback.RpcCallBackResponse getRpcCallBackResponse();
  /**
   * <code>.RpcCallBackResponse rpcCallBackResponse = 1;</code>
   */
  com.ops.sc.rpc.grpc.callback.RpcCallBackResponseOrBuilder getRpcCallBackResponseOrBuilder();

  /**
   * <code>string appName = 2;</code>
   */
  java.lang.String getAppName();
  /**
   * <code>string appName = 2;</code>
   */
  com.google.protobuf.ByteString
      getAppNameBytes();

  /**
   * <code>string uid = 3;</code>
   */
  java.lang.String getUid();
  /**
   * <code>string uid = 3;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();
}
