// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthCheck.proto

package com.ops.sc.rpc.health;

public final class HealthCheck {
  private HealthCheck() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HealthCheckRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ops.sc.rpc.health.HealthCheckRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string service = 1;</code>
     */
    java.lang.String getService();
    /**
     * <code>string service = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceBytes();
  }
  /**
   * Protobuf type {@code com.ops.sc.rpc.health.HealthCheckRequest}
   */
  public  static final class HealthCheckRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ops.sc.rpc.health.HealthCheckRequest)
      HealthCheckRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HealthCheckRequest.newBuilder() to construct.
    private HealthCheckRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HealthCheckRequest() {
      service_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HealthCheckRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              service_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ops.sc.rpc.health.HealthCheck.internal_static_com_ops_sc_rpc_health_HealthCheckRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ops.sc.rpc.health.HealthCheck.internal_static_com_ops_sc_rpc_health_HealthCheckRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest.class, com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest.Builder.class);
    }

    public static final int SERVICE_FIELD_NUMBER = 1;
    private volatile java.lang.Object service_;
    /**
     * <code>string service = 1;</code>
     */
    public java.lang.String getService() {
      java.lang.Object ref = service_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        service_ = s;
        return s;
      }
    }
    /**
     * <code>string service = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceBytes() {
      java.lang.Object ref = service_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        service_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getServiceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, service_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getServiceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, service_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest)) {
        return super.equals(obj);
      }
      com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest other = (com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest) obj;

      boolean result = true;
      result = result && getService()
          .equals(other.getService());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVICE_FIELD_NUMBER;
      hash = (53 * hash) + getService().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ops.sc.rpc.health.HealthCheckRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ops.sc.rpc.health.HealthCheckRequest)
        com.ops.sc.rpc.health.HealthCheck.HealthCheckRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ops.sc.rpc.health.HealthCheck.internal_static_com_ops_sc_rpc_health_HealthCheckRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ops.sc.rpc.health.HealthCheck.internal_static_com_ops_sc_rpc_health_HealthCheckRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest.class, com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest.Builder.class);
      }

      // Construct using com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        service_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ops.sc.rpc.health.HealthCheck.internal_static_com_ops_sc_rpc_health_HealthCheckRequest_descriptor;
      }

      @java.lang.Override
      public com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest getDefaultInstanceForType() {
        return com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest build() {
        com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest buildPartial() {
        com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest result = new com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest(this);
        result.service_ = service_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest) {
          return mergeFrom((com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest other) {
        if (other == com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest.getDefaultInstance()) return this;
        if (!other.getService().isEmpty()) {
          service_ = other.service_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object service_ = "";
      /**
       * <code>string service = 1;</code>
       */
      public java.lang.String getService() {
        java.lang.Object ref = service_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          service_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string service = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceBytes() {
        java.lang.Object ref = service_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          service_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string service = 1;</code>
       */
      public Builder setService(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        service_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string service = 1;</code>
       */
      public Builder clearService() {
        
        service_ = getDefaultInstance().getService();
        onChanged();
        return this;
      }
      /**
       * <code>string service = 1;</code>
       */
      public Builder setServiceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        service_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ops.sc.rpc.health.HealthCheckRequest)
    }

    // @@protoc_insertion_point(class_scope:com.ops.sc.rpc.health.HealthCheckRequest)
    private static final com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest();
    }

    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HealthCheckRequest>
        PARSER = new com.google.protobuf.AbstractParser<HealthCheckRequest>() {
      @java.lang.Override
      public HealthCheckRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HealthCheckRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HealthCheckRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HealthCheckRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ops.sc.rpc.health.HealthCheck.HealthCheckRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HealthCheckResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ops.sc.rpc.health.HealthCheckResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.ops.sc.rpc.health.HealthCheckResponse.ServingStatus status = 1;</code>
     */
    int getStatusValue();
    /**
     * <code>.com.ops.sc.rpc.health.HealthCheckResponse.ServingStatus status = 1;</code>
     */
    com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.ServingStatus getStatus();
  }
  /**
   * Protobuf type {@code com.ops.sc.rpc.health.HealthCheckResponse}
   */
  public  static final class HealthCheckResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ops.sc.rpc.health.HealthCheckResponse)
      HealthCheckResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HealthCheckResponse.newBuilder() to construct.
    private HealthCheckResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HealthCheckResponse() {
      status_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HealthCheckResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ops.sc.rpc.health.HealthCheck.internal_static_com_ops_sc_rpc_health_HealthCheckResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ops.sc.rpc.health.HealthCheck.internal_static_com_ops_sc_rpc_health_HealthCheckResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.class, com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code com.ops.sc.rpc.health.HealthCheckResponse.ServingStatus}
     */
    public enum ServingStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>SERVING = 1;</code>
       */
      SERVING(1),
      /**
       * <code>NOT_SERVING = 2;</code>
       */
      NOT_SERVING(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>SERVING = 1;</code>
       */
      public static final int SERVING_VALUE = 1;
      /**
       * <code>NOT_SERVING = 2;</code>
       */
      public static final int NOT_SERVING_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ServingStatus valueOf(int value) {
        return forNumber(value);
      }

      public static ServingStatus forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return SERVING;
          case 2: return NOT_SERVING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ServingStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ServingStatus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ServingStatus>() {
              public ServingStatus findValueByNumber(int number) {
                return ServingStatus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final ServingStatus[] VALUES = values();

      public static ServingStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ServingStatus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.ops.sc.rpc.health.HealthCheckResponse.ServingStatus)
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.com.ops.sc.rpc.health.HealthCheckResponse.ServingStatus status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.ops.sc.rpc.health.HealthCheckResponse.ServingStatus status = 1;</code>
     */
    public com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.ServingStatus getStatus() {
      @SuppressWarnings("deprecation")
      com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.ServingStatus result = com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.ServingStatus.valueOf(status_);
      return result == null ? com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.ServingStatus.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.ServingStatus.UNKNOWN.getNumber()) {
        output.writeEnum(1, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.ServingStatus.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse)) {
        return super.equals(obj);
      }
      com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse other = (com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse) obj;

      boolean result = true;
      result = result && status_ == other.status_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ops.sc.rpc.health.HealthCheckResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ops.sc.rpc.health.HealthCheckResponse)
        com.ops.sc.rpc.health.HealthCheck.HealthCheckResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ops.sc.rpc.health.HealthCheck.internal_static_com_ops_sc_rpc_health_HealthCheckResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ops.sc.rpc.health.HealthCheck.internal_static_com_ops_sc_rpc_health_HealthCheckResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.class, com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.Builder.class);
      }

      // Construct using com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ops.sc.rpc.health.HealthCheck.internal_static_com_ops_sc_rpc_health_HealthCheckResponse_descriptor;
      }

      @java.lang.Override
      public com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse getDefaultInstanceForType() {
        return com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse build() {
        com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse buildPartial() {
        com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse result = new com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse(this);
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse) {
          return mergeFrom((com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse other) {
        if (other == com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.com.ops.sc.rpc.health.HealthCheckResponse.ServingStatus status = 1;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.com.ops.sc.rpc.health.HealthCheckResponse.ServingStatus status = 1;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.ops.sc.rpc.health.HealthCheckResponse.ServingStatus status = 1;</code>
       */
      public com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.ServingStatus getStatus() {
        @SuppressWarnings("deprecation")
        com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.ServingStatus result = com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.ServingStatus.valueOf(status_);
        return result == null ? com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.ServingStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.ops.sc.rpc.health.HealthCheckResponse.ServingStatus status = 1;</code>
       */
      public Builder setStatus(com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse.ServingStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.ops.sc.rpc.health.HealthCheckResponse.ServingStatus status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ops.sc.rpc.health.HealthCheckResponse)
    }

    // @@protoc_insertion_point(class_scope:com.ops.sc.rpc.health.HealthCheckResponse)
    private static final com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse();
    }

    public static com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HealthCheckResponse>
        PARSER = new com.google.protobuf.AbstractParser<HealthCheckResponse>() {
      @java.lang.Override
      public HealthCheckResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HealthCheckResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HealthCheckResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HealthCheckResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ops.sc.rpc.health.HealthCheck.HealthCheckResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ops_sc_rpc_health_HealthCheckRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ops_sc_rpc_health_HealthCheckRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ops_sc_rpc_health_HealthCheckResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ops_sc_rpc_health_HealthCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021healthCheck.proto\022\025com.ops.sc.rpc.heal" +
      "th\"%\n\022HealthCheckRequest\022\017\n\007service\030\001 \001(" +
      "\t\"\233\001\n\023HealthCheckResponse\022H\n\006status\030\001 \001(" +
      "\01628.com.ops.sc.rpc.health.HealthCheckRes" +
      "ponse.ServingStatus\":\n\rServingStatus\022\013\n\007" +
      "UNKNOWN\020\000\022\013\n\007SERVING\020\001\022\017\n\013NOT_SERVING\020\0022" +
      "\314\001\n\006Health\022^\n\005Check\022).com.ops.sc.rpc.hea" +
      "lth.HealthCheckRequest\032*.com.ops.sc.rpc." +
      "health.HealthCheckResponse\022b\n\007Observe\022)." +
      "com.ops.sc.rpc.health.HealthCheckRequest" +
      "\032*.com.ops.sc.rpc.health.HealthCheckResp" +
      "onse0\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ops_sc_rpc_health_HealthCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ops_sc_rpc_health_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ops_sc_rpc_health_HealthCheckRequest_descriptor,
        new java.lang.String[] { "Service", });
    internal_static_com_ops_sc_rpc_health_HealthCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ops_sc_rpc_health_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ops_sc_rpc_health_HealthCheckResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
