// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: branchTransQueryRequest.proto

package com.ops.sc.rpc.dto;

/**
 * Protobuf type {@code BranchTransInfoList}
 */
public  final class BranchTransInfoList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BranchTransInfoList)
    BranchTransInfoListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BranchTransInfoList.newBuilder() to construct.
  private BranchTransInfoList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BranchTransInfoList() {
    branchTransInfos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BranchTransInfoList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              branchTransInfos_ = new java.util.ArrayList<com.ops.sc.rpc.dto.BranchTransInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            branchTransInfos_.add(
                input.readMessage(com.ops.sc.rpc.dto.BranchTransInfo.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        branchTransInfos_ = java.util.Collections.unmodifiableList(branchTransInfos_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ops.sc.rpc.dto.BranchTransQueryRequestOuterClass.internal_static_BranchTransInfoList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ops.sc.rpc.dto.BranchTransQueryRequestOuterClass.internal_static_BranchTransInfoList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ops.sc.rpc.dto.BranchTransInfoList.class, com.ops.sc.rpc.dto.BranchTransInfoList.Builder.class);
  }

  public static final int BRANCHTRANSINFOS_FIELD_NUMBER = 1;
  private java.util.List<com.ops.sc.rpc.dto.BranchTransInfo> branchTransInfos_;
  /**
   * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
   */
  public java.util.List<com.ops.sc.rpc.dto.BranchTransInfo> getBranchTransInfosList() {
    return branchTransInfos_;
  }
  /**
   * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
   */
  public java.util.List<? extends com.ops.sc.rpc.dto.BranchTransInfoOrBuilder> 
      getBranchTransInfosOrBuilderList() {
    return branchTransInfos_;
  }
  /**
   * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
   */
  public int getBranchTransInfosCount() {
    return branchTransInfos_.size();
  }
  /**
   * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
   */
  public com.ops.sc.rpc.dto.BranchTransInfo getBranchTransInfos(int index) {
    return branchTransInfos_.get(index);
  }
  /**
   * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
   */
  public com.ops.sc.rpc.dto.BranchTransInfoOrBuilder getBranchTransInfosOrBuilder(
      int index) {
    return branchTransInfos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < branchTransInfos_.size(); i++) {
      output.writeMessage(1, branchTransInfos_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < branchTransInfos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, branchTransInfos_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ops.sc.rpc.dto.BranchTransInfoList)) {
      return super.equals(obj);
    }
    com.ops.sc.rpc.dto.BranchTransInfoList other = (com.ops.sc.rpc.dto.BranchTransInfoList) obj;

    boolean result = true;
    result = result && getBranchTransInfosList()
        .equals(other.getBranchTransInfosList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBranchTransInfosCount() > 0) {
      hash = (37 * hash) + BRANCHTRANSINFOS_FIELD_NUMBER;
      hash = (53 * hash) + getBranchTransInfosList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ops.sc.rpc.dto.BranchTransInfoList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ops.sc.rpc.dto.BranchTransInfoList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ops.sc.rpc.dto.BranchTransInfoList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ops.sc.rpc.dto.BranchTransInfoList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ops.sc.rpc.dto.BranchTransInfoList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ops.sc.rpc.dto.BranchTransInfoList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ops.sc.rpc.dto.BranchTransInfoList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ops.sc.rpc.dto.BranchTransInfoList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ops.sc.rpc.dto.BranchTransInfoList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ops.sc.rpc.dto.BranchTransInfoList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ops.sc.rpc.dto.BranchTransInfoList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ops.sc.rpc.dto.BranchTransInfoList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ops.sc.rpc.dto.BranchTransInfoList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BranchTransInfoList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BranchTransInfoList)
      com.ops.sc.rpc.dto.BranchTransInfoListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ops.sc.rpc.dto.BranchTransQueryRequestOuterClass.internal_static_BranchTransInfoList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ops.sc.rpc.dto.BranchTransQueryRequestOuterClass.internal_static_BranchTransInfoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ops.sc.rpc.dto.BranchTransInfoList.class, com.ops.sc.rpc.dto.BranchTransInfoList.Builder.class);
    }

    // Construct using com.ops.sc.rpc.dto.BranchTransInfoList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBranchTransInfosFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (branchTransInfosBuilder_ == null) {
        branchTransInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        branchTransInfosBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ops.sc.rpc.dto.BranchTransQueryRequestOuterClass.internal_static_BranchTransInfoList_descriptor;
    }

    @java.lang.Override
    public com.ops.sc.rpc.dto.BranchTransInfoList getDefaultInstanceForType() {
      return com.ops.sc.rpc.dto.BranchTransInfoList.getDefaultInstance();
    }

    @java.lang.Override
    public com.ops.sc.rpc.dto.BranchTransInfoList build() {
      com.ops.sc.rpc.dto.BranchTransInfoList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ops.sc.rpc.dto.BranchTransInfoList buildPartial() {
      com.ops.sc.rpc.dto.BranchTransInfoList result = new com.ops.sc.rpc.dto.BranchTransInfoList(this);
      int from_bitField0_ = bitField0_;
      if (branchTransInfosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          branchTransInfos_ = java.util.Collections.unmodifiableList(branchTransInfos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.branchTransInfos_ = branchTransInfos_;
      } else {
        result.branchTransInfos_ = branchTransInfosBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ops.sc.rpc.dto.BranchTransInfoList) {
        return mergeFrom((com.ops.sc.rpc.dto.BranchTransInfoList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ops.sc.rpc.dto.BranchTransInfoList other) {
      if (other == com.ops.sc.rpc.dto.BranchTransInfoList.getDefaultInstance()) return this;
      if (branchTransInfosBuilder_ == null) {
        if (!other.branchTransInfos_.isEmpty()) {
          if (branchTransInfos_.isEmpty()) {
            branchTransInfos_ = other.branchTransInfos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBranchTransInfosIsMutable();
            branchTransInfos_.addAll(other.branchTransInfos_);
          }
          onChanged();
        }
      } else {
        if (!other.branchTransInfos_.isEmpty()) {
          if (branchTransInfosBuilder_.isEmpty()) {
            branchTransInfosBuilder_.dispose();
            branchTransInfosBuilder_ = null;
            branchTransInfos_ = other.branchTransInfos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            branchTransInfosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBranchTransInfosFieldBuilder() : null;
          } else {
            branchTransInfosBuilder_.addAllMessages(other.branchTransInfos_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ops.sc.rpc.dto.BranchTransInfoList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ops.sc.rpc.dto.BranchTransInfoList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.ops.sc.rpc.dto.BranchTransInfo> branchTransInfos_ =
      java.util.Collections.emptyList();
    private void ensureBranchTransInfosIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        branchTransInfos_ = new java.util.ArrayList<com.ops.sc.rpc.dto.BranchTransInfo>(branchTransInfos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ops.sc.rpc.dto.BranchTransInfo, com.ops.sc.rpc.dto.BranchTransInfo.Builder, com.ops.sc.rpc.dto.BranchTransInfoOrBuilder> branchTransInfosBuilder_;

    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public java.util.List<com.ops.sc.rpc.dto.BranchTransInfo> getBranchTransInfosList() {
      if (branchTransInfosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(branchTransInfos_);
      } else {
        return branchTransInfosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public int getBranchTransInfosCount() {
      if (branchTransInfosBuilder_ == null) {
        return branchTransInfos_.size();
      } else {
        return branchTransInfosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public com.ops.sc.rpc.dto.BranchTransInfo getBranchTransInfos(int index) {
      if (branchTransInfosBuilder_ == null) {
        return branchTransInfos_.get(index);
      } else {
        return branchTransInfosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public Builder setBranchTransInfos(
        int index, com.ops.sc.rpc.dto.BranchTransInfo value) {
      if (branchTransInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBranchTransInfosIsMutable();
        branchTransInfos_.set(index, value);
        onChanged();
      } else {
        branchTransInfosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public Builder setBranchTransInfos(
        int index, com.ops.sc.rpc.dto.BranchTransInfo.Builder builderForValue) {
      if (branchTransInfosBuilder_ == null) {
        ensureBranchTransInfosIsMutable();
        branchTransInfos_.set(index, builderForValue.build());
        onChanged();
      } else {
        branchTransInfosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public Builder addBranchTransInfos(com.ops.sc.rpc.dto.BranchTransInfo value) {
      if (branchTransInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBranchTransInfosIsMutable();
        branchTransInfos_.add(value);
        onChanged();
      } else {
        branchTransInfosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public Builder addBranchTransInfos(
        int index, com.ops.sc.rpc.dto.BranchTransInfo value) {
      if (branchTransInfosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBranchTransInfosIsMutable();
        branchTransInfos_.add(index, value);
        onChanged();
      } else {
        branchTransInfosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public Builder addBranchTransInfos(
        com.ops.sc.rpc.dto.BranchTransInfo.Builder builderForValue) {
      if (branchTransInfosBuilder_ == null) {
        ensureBranchTransInfosIsMutable();
        branchTransInfos_.add(builderForValue.build());
        onChanged();
      } else {
        branchTransInfosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public Builder addBranchTransInfos(
        int index, com.ops.sc.rpc.dto.BranchTransInfo.Builder builderForValue) {
      if (branchTransInfosBuilder_ == null) {
        ensureBranchTransInfosIsMutable();
        branchTransInfos_.add(index, builderForValue.build());
        onChanged();
      } else {
        branchTransInfosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public Builder addAllBranchTransInfos(
        java.lang.Iterable<? extends com.ops.sc.rpc.dto.BranchTransInfo> values) {
      if (branchTransInfosBuilder_ == null) {
        ensureBranchTransInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, branchTransInfos_);
        onChanged();
      } else {
        branchTransInfosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public Builder clearBranchTransInfos() {
      if (branchTransInfosBuilder_ == null) {
        branchTransInfos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        branchTransInfosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public Builder removeBranchTransInfos(int index) {
      if (branchTransInfosBuilder_ == null) {
        ensureBranchTransInfosIsMutable();
        branchTransInfos_.remove(index);
        onChanged();
      } else {
        branchTransInfosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public com.ops.sc.rpc.dto.BranchTransInfo.Builder getBranchTransInfosBuilder(
        int index) {
      return getBranchTransInfosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public com.ops.sc.rpc.dto.BranchTransInfoOrBuilder getBranchTransInfosOrBuilder(
        int index) {
      if (branchTransInfosBuilder_ == null) {
        return branchTransInfos_.get(index);  } else {
        return branchTransInfosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public java.util.List<? extends com.ops.sc.rpc.dto.BranchTransInfoOrBuilder> 
         getBranchTransInfosOrBuilderList() {
      if (branchTransInfosBuilder_ != null) {
        return branchTransInfosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(branchTransInfos_);
      }
    }
    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public com.ops.sc.rpc.dto.BranchTransInfo.Builder addBranchTransInfosBuilder() {
      return getBranchTransInfosFieldBuilder().addBuilder(
          com.ops.sc.rpc.dto.BranchTransInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public com.ops.sc.rpc.dto.BranchTransInfo.Builder addBranchTransInfosBuilder(
        int index) {
      return getBranchTransInfosFieldBuilder().addBuilder(
          index, com.ops.sc.rpc.dto.BranchTransInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .BranchTransInfo branchTransInfos = 1;</code>
     */
    public java.util.List<com.ops.sc.rpc.dto.BranchTransInfo.Builder> 
         getBranchTransInfosBuilderList() {
      return getBranchTransInfosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ops.sc.rpc.dto.BranchTransInfo, com.ops.sc.rpc.dto.BranchTransInfo.Builder, com.ops.sc.rpc.dto.BranchTransInfoOrBuilder> 
        getBranchTransInfosFieldBuilder() {
      if (branchTransInfosBuilder_ == null) {
        branchTransInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ops.sc.rpc.dto.BranchTransInfo, com.ops.sc.rpc.dto.BranchTransInfo.Builder, com.ops.sc.rpc.dto.BranchTransInfoOrBuilder>(
                branchTransInfos_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        branchTransInfos_ = null;
      }
      return branchTransInfosBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BranchTransInfoList)
  }

  // @@protoc_insertion_point(class_scope:BranchTransInfoList)
  private static final com.ops.sc.rpc.dto.BranchTransInfoList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ops.sc.rpc.dto.BranchTransInfoList();
  }

  public static com.ops.sc.rpc.dto.BranchTransInfoList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BranchTransInfoList>
      PARSER = new com.google.protobuf.AbstractParser<BranchTransInfoList>() {
    @java.lang.Override
    public BranchTransInfoList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BranchTransInfoList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BranchTransInfoList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BranchTransInfoList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ops.sc.rpc.dto.BranchTransInfoList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

