// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: branchTransQueryRequest.proto

package com.ops.sc.rpc.dto;

public interface BranchTransQueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BranchTransQueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestId = 1;</code>
   */
  java.lang.String getRequestId();
  /**
   * <code>string requestId = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>string tid = 2;</code>
   */
  java.lang.String getTid();
  /**
   * <code>string tid = 2;</code>
   */
  com.google.protobuf.ByteString
      getTidBytes();
}
