// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: globalRequest.proto

package com.ops.sc.rpc.dto;

/**
 * Protobuf type {@code GlobalTransRollbackRequest}
 */
public  final class GlobalTransRollbackRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GlobalTransRollbackRequest)
    GlobalTransRollbackRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GlobalTransRollbackRequest.newBuilder() to construct.
  private GlobalTransRollbackRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GlobalTransRollbackRequest() {
    businessId_ = "";
    tid_ = "";
    transMode_ = "";
    isSync_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GlobalTransRollbackRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            businessId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            tid_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            transMode_ = s;
            break;
          }
          case 32: {

            isSync_ = input.readBool();
            break;
          }
          case 42: {
            com.google.protobuf.UInt64Value.Builder subBuilder = null;
            if (timeout_ != null) {
              subBuilder = timeout_.toBuilder();
            }
            timeout_ = input.readMessage(com.google.protobuf.UInt64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timeout_);
              timeout_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.google.protobuf.UInt32Value.Builder subBuilder = null;
            if (timeOutType_ != null) {
              subBuilder = timeOutType_.toBuilder();
            }
            timeOutType_ = input.readMessage(com.google.protobuf.UInt32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timeOutType_);
              timeOutType_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ops.sc.rpc.dto.GlobalRequest.internal_static_GlobalTransRollbackRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ops.sc.rpc.dto.GlobalRequest.internal_static_GlobalTransRollbackRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ops.sc.rpc.dto.GlobalTransRollbackRequest.class, com.ops.sc.rpc.dto.GlobalTransRollbackRequest.Builder.class);
  }

  public static final int BUSINESSID_FIELD_NUMBER = 1;
  private volatile java.lang.Object businessId_;
  /**
   * <code>string businessId = 1;</code>
   */
  public java.lang.String getBusinessId() {
    java.lang.Object ref = businessId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      businessId_ = s;
      return s;
    }
  }
  /**
   * <code>string businessId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBusinessIdBytes() {
    java.lang.Object ref = businessId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      businessId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TID_FIELD_NUMBER = 2;
  private volatile java.lang.Object tid_;
  /**
   * <code>string tid = 2;</code>
   */
  public java.lang.String getTid() {
    java.lang.Object ref = tid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tid_ = s;
      return s;
    }
  }
  /**
   * <code>string tid = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTidBytes() {
    java.lang.Object ref = tid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSMODE_FIELD_NUMBER = 3;
  private volatile java.lang.Object transMode_;
  /**
   * <code>string transMode = 3;</code>
   */
  public java.lang.String getTransMode() {
    java.lang.Object ref = transMode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transMode_ = s;
      return s;
    }
  }
  /**
   * <code>string transMode = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTransModeBytes() {
    java.lang.Object ref = transMode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transMode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISSYNC_FIELD_NUMBER = 4;
  private boolean isSync_;
  /**
   * <code>bool isSync = 4;</code>
   */
  public boolean getIsSync() {
    return isSync_;
  }

  public static final int TIMEOUT_FIELD_NUMBER = 5;
  private com.google.protobuf.UInt64Value timeout_;
  /**
   * <code>.google.protobuf.UInt64Value timeout = 5;</code>
   */
  public boolean hasTimeout() {
    return timeout_ != null;
  }
  /**
   * <code>.google.protobuf.UInt64Value timeout = 5;</code>
   */
  public com.google.protobuf.UInt64Value getTimeout() {
    return timeout_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : timeout_;
  }
  /**
   * <code>.google.protobuf.UInt64Value timeout = 5;</code>
   */
  public com.google.protobuf.UInt64ValueOrBuilder getTimeoutOrBuilder() {
    return getTimeout();
  }

  public static final int TIMEOUTTYPE_FIELD_NUMBER = 6;
  private com.google.protobuf.UInt32Value timeOutType_;
  /**
   * <code>.google.protobuf.UInt32Value timeOutType = 6;</code>
   */
  public boolean hasTimeOutType() {
    return timeOutType_ != null;
  }
  /**
   * <code>.google.protobuf.UInt32Value timeOutType = 6;</code>
   */
  public com.google.protobuf.UInt32Value getTimeOutType() {
    return timeOutType_ == null ? com.google.protobuf.UInt32Value.getDefaultInstance() : timeOutType_;
  }
  /**
   * <code>.google.protobuf.UInt32Value timeOutType = 6;</code>
   */
  public com.google.protobuf.UInt32ValueOrBuilder getTimeOutTypeOrBuilder() {
    return getTimeOutType();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBusinessIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, businessId_);
    }
    if (!getTidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tid_);
    }
    if (!getTransModeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, transMode_);
    }
    if (isSync_ != false) {
      output.writeBool(4, isSync_);
    }
    if (timeout_ != null) {
      output.writeMessage(5, getTimeout());
    }
    if (timeOutType_ != null) {
      output.writeMessage(6, getTimeOutType());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBusinessIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, businessId_);
    }
    if (!getTidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tid_);
    }
    if (!getTransModeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, transMode_);
    }
    if (isSync_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isSync_);
    }
    if (timeout_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getTimeout());
    }
    if (timeOutType_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getTimeOutType());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ops.sc.rpc.dto.GlobalTransRollbackRequest)) {
      return super.equals(obj);
    }
    com.ops.sc.rpc.dto.GlobalTransRollbackRequest other = (com.ops.sc.rpc.dto.GlobalTransRollbackRequest) obj;

    boolean result = true;
    result = result && getBusinessId()
        .equals(other.getBusinessId());
    result = result && getTid()
        .equals(other.getTid());
    result = result && getTransMode()
        .equals(other.getTransMode());
    result = result && (getIsSync()
        == other.getIsSync());
    result = result && (hasTimeout() == other.hasTimeout());
    if (hasTimeout()) {
      result = result && getTimeout()
          .equals(other.getTimeout());
    }
    result = result && (hasTimeOutType() == other.hasTimeOutType());
    if (hasTimeOutType()) {
      result = result && getTimeOutType()
          .equals(other.getTimeOutType());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BUSINESSID_FIELD_NUMBER;
    hash = (53 * hash) + getBusinessId().hashCode();
    hash = (37 * hash) + TID_FIELD_NUMBER;
    hash = (53 * hash) + getTid().hashCode();
    hash = (37 * hash) + TRANSMODE_FIELD_NUMBER;
    hash = (53 * hash) + getTransMode().hashCode();
    hash = (37 * hash) + ISSYNC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSync());
    if (hasTimeout()) {
      hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
      hash = (53 * hash) + getTimeout().hashCode();
    }
    if (hasTimeOutType()) {
      hash = (37 * hash) + TIMEOUTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getTimeOutType().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ops.sc.rpc.dto.GlobalTransRollbackRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ops.sc.rpc.dto.GlobalTransRollbackRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ops.sc.rpc.dto.GlobalTransRollbackRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ops.sc.rpc.dto.GlobalTransRollbackRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ops.sc.rpc.dto.GlobalTransRollbackRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ops.sc.rpc.dto.GlobalTransRollbackRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ops.sc.rpc.dto.GlobalTransRollbackRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ops.sc.rpc.dto.GlobalTransRollbackRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ops.sc.rpc.dto.GlobalTransRollbackRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ops.sc.rpc.dto.GlobalTransRollbackRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ops.sc.rpc.dto.GlobalTransRollbackRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ops.sc.rpc.dto.GlobalTransRollbackRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ops.sc.rpc.dto.GlobalTransRollbackRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GlobalTransRollbackRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GlobalTransRollbackRequest)
      com.ops.sc.rpc.dto.GlobalTransRollbackRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ops.sc.rpc.dto.GlobalRequest.internal_static_GlobalTransRollbackRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ops.sc.rpc.dto.GlobalRequest.internal_static_GlobalTransRollbackRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ops.sc.rpc.dto.GlobalTransRollbackRequest.class, com.ops.sc.rpc.dto.GlobalTransRollbackRequest.Builder.class);
    }

    // Construct using com.ops.sc.rpc.dto.GlobalTransRollbackRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      businessId_ = "";

      tid_ = "";

      transMode_ = "";

      isSync_ = false;

      if (timeoutBuilder_ == null) {
        timeout_ = null;
      } else {
        timeout_ = null;
        timeoutBuilder_ = null;
      }
      if (timeOutTypeBuilder_ == null) {
        timeOutType_ = null;
      } else {
        timeOutType_ = null;
        timeOutTypeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ops.sc.rpc.dto.GlobalRequest.internal_static_GlobalTransRollbackRequest_descriptor;
    }

    @java.lang.Override
    public com.ops.sc.rpc.dto.GlobalTransRollbackRequest getDefaultInstanceForType() {
      return com.ops.sc.rpc.dto.GlobalTransRollbackRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ops.sc.rpc.dto.GlobalTransRollbackRequest build() {
      com.ops.sc.rpc.dto.GlobalTransRollbackRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ops.sc.rpc.dto.GlobalTransRollbackRequest buildPartial() {
      com.ops.sc.rpc.dto.GlobalTransRollbackRequest result = new com.ops.sc.rpc.dto.GlobalTransRollbackRequest(this);
      result.businessId_ = businessId_;
      result.tid_ = tid_;
      result.transMode_ = transMode_;
      result.isSync_ = isSync_;
      if (timeoutBuilder_ == null) {
        result.timeout_ = timeout_;
      } else {
        result.timeout_ = timeoutBuilder_.build();
      }
      if (timeOutTypeBuilder_ == null) {
        result.timeOutType_ = timeOutType_;
      } else {
        result.timeOutType_ = timeOutTypeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ops.sc.rpc.dto.GlobalTransRollbackRequest) {
        return mergeFrom((com.ops.sc.rpc.dto.GlobalTransRollbackRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ops.sc.rpc.dto.GlobalTransRollbackRequest other) {
      if (other == com.ops.sc.rpc.dto.GlobalTransRollbackRequest.getDefaultInstance()) return this;
      if (!other.getBusinessId().isEmpty()) {
        businessId_ = other.businessId_;
        onChanged();
      }
      if (!other.getTid().isEmpty()) {
        tid_ = other.tid_;
        onChanged();
      }
      if (!other.getTransMode().isEmpty()) {
        transMode_ = other.transMode_;
        onChanged();
      }
      if (other.getIsSync() != false) {
        setIsSync(other.getIsSync());
      }
      if (other.hasTimeout()) {
        mergeTimeout(other.getTimeout());
      }
      if (other.hasTimeOutType()) {
        mergeTimeOutType(other.getTimeOutType());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ops.sc.rpc.dto.GlobalTransRollbackRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ops.sc.rpc.dto.GlobalTransRollbackRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object businessId_ = "";
    /**
     * <code>string businessId = 1;</code>
     */
    public java.lang.String getBusinessId() {
      java.lang.Object ref = businessId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        businessId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string businessId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBusinessIdBytes() {
      java.lang.Object ref = businessId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        businessId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string businessId = 1;</code>
     */
    public Builder setBusinessId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      businessId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string businessId = 1;</code>
     */
    public Builder clearBusinessId() {
      
      businessId_ = getDefaultInstance().getBusinessId();
      onChanged();
      return this;
    }
    /**
     * <code>string businessId = 1;</code>
     */
    public Builder setBusinessIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      businessId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tid_ = "";
    /**
     * <code>string tid = 2;</code>
     */
    public java.lang.String getTid() {
      java.lang.Object ref = tid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTidBytes() {
      java.lang.Object ref = tid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tid = 2;</code>
     */
    public Builder setTid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tid = 2;</code>
     */
    public Builder clearTid() {
      
      tid_ = getDefaultInstance().getTid();
      onChanged();
      return this;
    }
    /**
     * <code>string tid = 2;</code>
     */
    public Builder setTidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object transMode_ = "";
    /**
     * <code>string transMode = 3;</code>
     */
    public java.lang.String getTransMode() {
      java.lang.Object ref = transMode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transMode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transMode = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTransModeBytes() {
      java.lang.Object ref = transMode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transMode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transMode = 3;</code>
     */
    public Builder setTransMode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transMode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string transMode = 3;</code>
     */
    public Builder clearTransMode() {
      
      transMode_ = getDefaultInstance().getTransMode();
      onChanged();
      return this;
    }
    /**
     * <code>string transMode = 3;</code>
     */
    public Builder setTransModeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transMode_ = value;
      onChanged();
      return this;
    }

    private boolean isSync_ ;
    /**
     * <code>bool isSync = 4;</code>
     */
    public boolean getIsSync() {
      return isSync_;
    }
    /**
     * <code>bool isSync = 4;</code>
     */
    public Builder setIsSync(boolean value) {
      
      isSync_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isSync = 4;</code>
     */
    public Builder clearIsSync() {
      
      isSync_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.UInt64Value timeout_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder> timeoutBuilder_;
    /**
     * <code>.google.protobuf.UInt64Value timeout = 5;</code>
     */
    public boolean hasTimeout() {
      return timeoutBuilder_ != null || timeout_ != null;
    }
    /**
     * <code>.google.protobuf.UInt64Value timeout = 5;</code>
     */
    public com.google.protobuf.UInt64Value getTimeout() {
      if (timeoutBuilder_ == null) {
        return timeout_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : timeout_;
      } else {
        return timeoutBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.UInt64Value timeout = 5;</code>
     */
    public Builder setTimeout(com.google.protobuf.UInt64Value value) {
      if (timeoutBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timeout_ = value;
        onChanged();
      } else {
        timeoutBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value timeout = 5;</code>
     */
    public Builder setTimeout(
        com.google.protobuf.UInt64Value.Builder builderForValue) {
      if (timeoutBuilder_ == null) {
        timeout_ = builderForValue.build();
        onChanged();
      } else {
        timeoutBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value timeout = 5;</code>
     */
    public Builder mergeTimeout(com.google.protobuf.UInt64Value value) {
      if (timeoutBuilder_ == null) {
        if (timeout_ != null) {
          timeout_ =
            com.google.protobuf.UInt64Value.newBuilder(timeout_).mergeFrom(value).buildPartial();
        } else {
          timeout_ = value;
        }
        onChanged();
      } else {
        timeoutBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value timeout = 5;</code>
     */
    public Builder clearTimeout() {
      if (timeoutBuilder_ == null) {
        timeout_ = null;
        onChanged();
      } else {
        timeout_ = null;
        timeoutBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value timeout = 5;</code>
     */
    public com.google.protobuf.UInt64Value.Builder getTimeoutBuilder() {
      
      onChanged();
      return getTimeoutFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.UInt64Value timeout = 5;</code>
     */
    public com.google.protobuf.UInt64ValueOrBuilder getTimeoutOrBuilder() {
      if (timeoutBuilder_ != null) {
        return timeoutBuilder_.getMessageOrBuilder();
      } else {
        return timeout_ == null ?
            com.google.protobuf.UInt64Value.getDefaultInstance() : timeout_;
      }
    }
    /**
     * <code>.google.protobuf.UInt64Value timeout = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder> 
        getTimeoutFieldBuilder() {
      if (timeoutBuilder_ == null) {
        timeoutBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder>(
                getTimeout(),
                getParentForChildren(),
                isClean());
        timeout_ = null;
      }
      return timeoutBuilder_;
    }

    private com.google.protobuf.UInt32Value timeOutType_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt32Value, com.google.protobuf.UInt32Value.Builder, com.google.protobuf.UInt32ValueOrBuilder> timeOutTypeBuilder_;
    /**
     * <code>.google.protobuf.UInt32Value timeOutType = 6;</code>
     */
    public boolean hasTimeOutType() {
      return timeOutTypeBuilder_ != null || timeOutType_ != null;
    }
    /**
     * <code>.google.protobuf.UInt32Value timeOutType = 6;</code>
     */
    public com.google.protobuf.UInt32Value getTimeOutType() {
      if (timeOutTypeBuilder_ == null) {
        return timeOutType_ == null ? com.google.protobuf.UInt32Value.getDefaultInstance() : timeOutType_;
      } else {
        return timeOutTypeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.UInt32Value timeOutType = 6;</code>
     */
    public Builder setTimeOutType(com.google.protobuf.UInt32Value value) {
      if (timeOutTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timeOutType_ = value;
        onChanged();
      } else {
        timeOutTypeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt32Value timeOutType = 6;</code>
     */
    public Builder setTimeOutType(
        com.google.protobuf.UInt32Value.Builder builderForValue) {
      if (timeOutTypeBuilder_ == null) {
        timeOutType_ = builderForValue.build();
        onChanged();
      } else {
        timeOutTypeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt32Value timeOutType = 6;</code>
     */
    public Builder mergeTimeOutType(com.google.protobuf.UInt32Value value) {
      if (timeOutTypeBuilder_ == null) {
        if (timeOutType_ != null) {
          timeOutType_ =
            com.google.protobuf.UInt32Value.newBuilder(timeOutType_).mergeFrom(value).buildPartial();
        } else {
          timeOutType_ = value;
        }
        onChanged();
      } else {
        timeOutTypeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt32Value timeOutType = 6;</code>
     */
    public Builder clearTimeOutType() {
      if (timeOutTypeBuilder_ == null) {
        timeOutType_ = null;
        onChanged();
      } else {
        timeOutType_ = null;
        timeOutTypeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt32Value timeOutType = 6;</code>
     */
    public com.google.protobuf.UInt32Value.Builder getTimeOutTypeBuilder() {
      
      onChanged();
      return getTimeOutTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.UInt32Value timeOutType = 6;</code>
     */
    public com.google.protobuf.UInt32ValueOrBuilder getTimeOutTypeOrBuilder() {
      if (timeOutTypeBuilder_ != null) {
        return timeOutTypeBuilder_.getMessageOrBuilder();
      } else {
        return timeOutType_ == null ?
            com.google.protobuf.UInt32Value.getDefaultInstance() : timeOutType_;
      }
    }
    /**
     * <code>.google.protobuf.UInt32Value timeOutType = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt32Value, com.google.protobuf.UInt32Value.Builder, com.google.protobuf.UInt32ValueOrBuilder> 
        getTimeOutTypeFieldBuilder() {
      if (timeOutTypeBuilder_ == null) {
        timeOutTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.UInt32Value, com.google.protobuf.UInt32Value.Builder, com.google.protobuf.UInt32ValueOrBuilder>(
                getTimeOutType(),
                getParentForChildren(),
                isClean());
        timeOutType_ = null;
      }
      return timeOutTypeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GlobalTransRollbackRequest)
  }

  // @@protoc_insertion_point(class_scope:GlobalTransRollbackRequest)
  private static final com.ops.sc.rpc.dto.GlobalTransRollbackRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ops.sc.rpc.dto.GlobalTransRollbackRequest();
  }

  public static com.ops.sc.rpc.dto.GlobalTransRollbackRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GlobalTransRollbackRequest>
      PARSER = new com.google.protobuf.AbstractParser<GlobalTransRollbackRequest>() {
    @java.lang.Override
    public GlobalTransRollbackRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GlobalTransRollbackRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GlobalTransRollbackRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GlobalTransRollbackRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ops.sc.rpc.dto.GlobalTransRollbackRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

