// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: globalRequest.proto

package com.ops.sc.rpc.dto;

public final class GlobalRequest {
  private GlobalRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalTransRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalTransRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalTransRequest_BranchTransDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalTransRequest_BranchTransDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalTransRequest_BranchTransDetail_BranchParamEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalTransRequest_BranchTransDetail_BranchParamEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalTransRequest_BranchTransDetail_ExternalParamEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalTransRequest_BranchTransDetail_ExternalParamEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalTransRequest_BranchTransDetail_RollbackParamEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalTransRequest_BranchTransDetail_RollbackParamEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalTransRequest_MapValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalTransRequest_MapValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalTransResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalTransResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalTransRollbackRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalTransRollbackRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalTransRollbackResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalTransRollbackResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalSagaTransRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalSagaTransRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_BranchParamEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_BranchParamEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_BranchRollbackParamEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_BranchRollbackParamEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_ExternalParamEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_ExternalParamEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalSagaTransRequest_MapValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalSagaTransRequest_MapValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalSagaTransRequest_MapValue_ValueMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalSagaTransRequest_MapValue_ValueMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GlobalSagaTransResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GlobalSagaTransResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023globalRequest.proto\032\024parentResponse.pr" +
      "oto\032\036google/protobuf/wrappers.proto\"\230\t\n\022" +
      "GlobalTransRequest\022\022\n\nbusinessId\030\001 \001(\t\022\024" +
      "\n\014transGroupId\030\002 \001(\t\022\020\n\010callerIp\030\003 \001(\t\022\017" +
      "\n\007appName\030\004 \001(\t\022-\n\007timeout\030\005 \001(\0132\034.googl" +
      "e.protobuf.UInt64Value\0226\n\020callbackStrate" +
      "gy\030\006 \001(\0132\034.google.protobuf.UInt32Value\0221" +
      "\n\013timeoutType\030\007 \001(\0132\034.google.protobuf.UI" +
      "nt32Value\022\021\n\ttransMode\030\010 \001(\t\022\022\n\ndataSour" +
      "ce\030\t \001(\t\0224\n\016callInParallel\030\n \001(\0132\034.googl" +
      "e.protobuf.UInt32Value\022\024\n\014rollbackInfo\030\013" +
      " \001(\t\022\021\n\ttransType\030\014 \001(\t\022\020\n\010callMode\030\r \001(" +
      "\t\022A\n\022branchTransDetails\030\016 \003(\0132%.GlobalTr" +
      "ansRequest.BranchTransDetail\032\244\005\n\021BranchT" +
      "ransDetail\022\027\n\017branchTransName\030\001 \001(\t\022\022\n\nb" +
      "ranchName\030\002 \001(\t\022\027\n\017transactionName\030\003 \001(\t" +
      "\022K\n\013branchParam\030\004 \003(\01326.GlobalTransReque" +
      "st.BranchTransDetail.BranchParamEntry\022O\n" +
      "\rexternalParam\030\005 \003(\01328.GlobalTransReques" +
      "t.BranchTransDetail.ExternalParamEntry\022\021" +
      "\n\thasParent\030\006 \001(\010\022\031\n\021parentBranchNames\030\007" +
      " \003(\t\022-\n\007timeout\030\010 \001(\0132\034.google.protobuf." +
      "UInt64Value\0221\n\013timeOutType\030\t \001(\0132\034.googl" +
      "e.protobuf.UInt32Value\022\025\n\rretryRequired\030" +
      "\n \001(\010\022O\n\rrollbackParam\030\013 \003(\01328.GlobalTra" +
      "nsRequest.BranchTransDetail.RollbackPara" +
      "mEntry\022\023\n\013returnParam\030\014 \003(\t\0322\n\020BranchPar" +
      "amEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032" +
      "4\n\022ExternalParamEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\t:\0028\001\0324\n\022RollbackParamEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032\031\n\010MapValue\022" +
      "\r\n\005value\030\001 \003(\t\"\200\001\n\023GlobalTransResponse\022%" +
      "\n\014baseResponse\030\001 \001(\0132\017.ParentResponse\022\013\n" +
      "\003tid\030\002 \001(\t\0225\n\017checkBackMetaId\030\003 \001(\0132\034.go" +
      "ogle.protobuf.UInt64Value\"\302\001\n\032GlobalTran" +
      "sRollbackRequest\022\022\n\nbusinessId\030\001 \001(\t\022\013\n\003" +
      "tid\030\002 \001(\t\022\021\n\ttransMode\030\003 \001(\t\022\016\n\006isSync\030\004" +
      " \001(\010\022-\n\007timeout\030\005 \001(\0132\034.google.protobuf." +
      "UInt64Value\0221\n\013timeOutType\030\006 \001(\0132\034.googl" +
      "e.protobuf.UInt32Value\"D\n\033GlobalTransRol" +
      "lbackResponse\022%\n\014baseResponse\030\001 \001(\0132\017.Pa" +
      "rentResponse\"\230\t\n\026GlobalSagaTransRequest\022" +
      "\022\n\nbusinessId\030\001 \001(\t\022\024\n\014transGroupId\030\002 \001(" +
      "\t\022\020\n\010callerIp\030\003 \001(\t\022\017\n\007appName\030\004 \001(\t\022-\n\007" +
      "timeout\030\005 \001(\0132\034.google.protobuf.UInt64Va" +
      "lue\022\021\n\ttransName\030\006 \001(\t\0221\n\013timeoutType\030\007 " +
      "\001(\0132\034.google.protobuf.UInt32Value\022\021\n\ttra" +
      "nsMode\030\010 \001(\t\022\021\n\ttransType\030\t \001(\t\022\020\n\010callM" +
      "ode\030\n \001(\t\022I\n\022branchTransDetails\030\014 \003(\0132-." +
      "GlobalSagaTransRequest.BranchSagaTransDe" +
      "tail\032\271\005\n\025BranchSagaTransDetail\022\027\n\017branch" +
      "TransName\030\001 \001(\t\022\022\n\nbranchName\030\002 \001(\t\022S\n\013b" +
      "ranchParam\030\003 \003(\0132>.GlobalSagaTransReques" +
      "t.BranchSagaTransDetail.BranchParamEntry" +
      "\022c\n\023branchRollbackParam\030\004 \003(\0132F.GlobalSa" +
      "gaTransRequest.BranchSagaTransDetail.Bra" +
      "nchRollbackParamEntry\022W\n\rexternalParam\030\005" +
      " \003(\0132@.GlobalSagaTransRequest.BranchSaga" +
      "TransDetail.ExternalParamEntry\022\021\n\thasPar" +
      "ent\030\006 \001(\010\022\031\n\021parentBranchNames\030\007 \003(\t\022-\n\007" +
      "timeout\030\010 \001(\0132\034.google.protobuf.UInt64Va" +
      "lue\022\025\n\rretryRequired\030\t \001(\010\0221\n\013timeoutTyp" +
      "e\030\n \001(\0132\034.google.protobuf.UInt32Value\022\023\n" +
      "\013returnParam\030\013 \003(\t\0322\n\020BranchParamEntry\022\013" +
      "\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032:\n\030Branch" +
      "RollbackParamEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\t:\0028\001\0324\n\022ExternalParamEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032}\n\010MapValue\022@\n\010" +
      "valueMap\030\001 \003(\0132..GlobalSagaTransRequest." +
      "MapValue.ValueMapEntry\032/\n\rValueMapEntry\022" +
      "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"M\n\027Globa" +
      "lSagaTransResponse\022%\n\014baseResponse\030\001 \001(\013" +
      "2\017.ParentResponse\022\013\n\003tid\030\002 \001(\tB\035\n\022com.op" +
      "s.sc.rpc.dtoP\001\242\002\004HLWSb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ops.sc.rpc.dto.ParentResponseOuterClass.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_GlobalTransRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GlobalTransRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalTransRequest_descriptor,
        new java.lang.String[] { "BusinessId", "TransGroupId", "CallerIp", "AppName", "Timeout", "CallbackStrategy", "TimeoutType", "TransMode", "DataSource", "CallInParallel", "RollbackInfo", "TransType", "CallMode", "BranchTransDetails", });
    internal_static_GlobalTransRequest_BranchTransDetail_descriptor =
      internal_static_GlobalTransRequest_descriptor.getNestedTypes().get(0);
    internal_static_GlobalTransRequest_BranchTransDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalTransRequest_BranchTransDetail_descriptor,
        new java.lang.String[] { "BranchTransName", "BranchName", "TransactionName", "BranchParam", "ExternalParam", "HasParent", "ParentBranchNames", "Timeout", "TimeOutType", "RetryRequired", "RollbackParam", "ReturnParam", });
    internal_static_GlobalTransRequest_BranchTransDetail_BranchParamEntry_descriptor =
      internal_static_GlobalTransRequest_BranchTransDetail_descriptor.getNestedTypes().get(0);
    internal_static_GlobalTransRequest_BranchTransDetail_BranchParamEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalTransRequest_BranchTransDetail_BranchParamEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_GlobalTransRequest_BranchTransDetail_ExternalParamEntry_descriptor =
      internal_static_GlobalTransRequest_BranchTransDetail_descriptor.getNestedTypes().get(1);
    internal_static_GlobalTransRequest_BranchTransDetail_ExternalParamEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalTransRequest_BranchTransDetail_ExternalParamEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_GlobalTransRequest_BranchTransDetail_RollbackParamEntry_descriptor =
      internal_static_GlobalTransRequest_BranchTransDetail_descriptor.getNestedTypes().get(2);
    internal_static_GlobalTransRequest_BranchTransDetail_RollbackParamEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalTransRequest_BranchTransDetail_RollbackParamEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_GlobalTransRequest_MapValue_descriptor =
      internal_static_GlobalTransRequest_descriptor.getNestedTypes().get(1);
    internal_static_GlobalTransRequest_MapValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalTransRequest_MapValue_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_GlobalTransResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GlobalTransResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalTransResponse_descriptor,
        new java.lang.String[] { "BaseResponse", "Tid", "CheckBackMetaId", });
    internal_static_GlobalTransRollbackRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GlobalTransRollbackRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalTransRollbackRequest_descriptor,
        new java.lang.String[] { "BusinessId", "Tid", "TransMode", "IsSync", "Timeout", "TimeOutType", });
    internal_static_GlobalTransRollbackResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GlobalTransRollbackResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalTransRollbackResponse_descriptor,
        new java.lang.String[] { "BaseResponse", });
    internal_static_GlobalSagaTransRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GlobalSagaTransRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalSagaTransRequest_descriptor,
        new java.lang.String[] { "BusinessId", "TransGroupId", "CallerIp", "AppName", "Timeout", "TransName", "TimeoutType", "TransMode", "TransType", "CallMode", "BranchTransDetails", });
    internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_descriptor =
      internal_static_GlobalSagaTransRequest_descriptor.getNestedTypes().get(0);
    internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_descriptor,
        new java.lang.String[] { "BranchTransName", "BranchName", "BranchParam", "BranchRollbackParam", "ExternalParam", "HasParent", "ParentBranchNames", "Timeout", "RetryRequired", "TimeoutType", "ReturnParam", });
    internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_BranchParamEntry_descriptor =
      internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_descriptor.getNestedTypes().get(0);
    internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_BranchParamEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_BranchParamEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_BranchRollbackParamEntry_descriptor =
      internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_descriptor.getNestedTypes().get(1);
    internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_BranchRollbackParamEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_BranchRollbackParamEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_ExternalParamEntry_descriptor =
      internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_descriptor.getNestedTypes().get(2);
    internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_ExternalParamEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalSagaTransRequest_BranchSagaTransDetail_ExternalParamEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_GlobalSagaTransRequest_MapValue_descriptor =
      internal_static_GlobalSagaTransRequest_descriptor.getNestedTypes().get(1);
    internal_static_GlobalSagaTransRequest_MapValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalSagaTransRequest_MapValue_descriptor,
        new java.lang.String[] { "ValueMap", });
    internal_static_GlobalSagaTransRequest_MapValue_ValueMapEntry_descriptor =
      internal_static_GlobalSagaTransRequest_MapValue_descriptor.getNestedTypes().get(0);
    internal_static_GlobalSagaTransRequest_MapValue_ValueMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalSagaTransRequest_MapValue_ValueMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_GlobalSagaTransResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GlobalSagaTransResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GlobalSagaTransResponse_descriptor,
        new java.lang.String[] { "BaseResponse", "Tid", });
    com.ops.sc.rpc.dto.ParentResponseOuterClass.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
