// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: globalRequest.proto

package com.ops.sc.rpc.dto;

public interface GlobalSagaTransRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GlobalSagaTransRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string businessId = 1;</code>
   */
  java.lang.String getBusinessId();
  /**
   * <code>string businessId = 1;</code>
   */
  com.google.protobuf.ByteString
      getBusinessIdBytes();

  /**
   * <code>string transGroupId = 2;</code>
   */
  java.lang.String getTransGroupId();
  /**
   * <code>string transGroupId = 2;</code>
   */
  com.google.protobuf.ByteString
      getTransGroupIdBytes();

  /**
   * <pre>
   * 调用方本机ip
   * </pre>
   *
   * <code>string callerIp = 3;</code>
   */
  java.lang.String getCallerIp();
  /**
   * <pre>
   * 调用方本机ip
   * </pre>
   *
   * <code>string callerIp = 3;</code>
   */
  com.google.protobuf.ByteString
      getCallerIpBytes();

  /**
   * <pre>
   * 应用名称
   * </pre>
   *
   * <code>string appName = 4;</code>
   */
  java.lang.String getAppName();
  /**
   * <pre>
   * 应用名称
   * </pre>
   *
   * <code>string appName = 4;</code>
   */
  com.google.protobuf.ByteString
      getAppNameBytes();

  /**
   * <pre>
   * 全局事务超时时间, 单位ms
   * </pre>
   *
   * <code>.google.protobuf.UInt64Value timeout = 5;</code>
   */
  boolean hasTimeout();
  /**
   * <pre>
   * 全局事务超时时间, 单位ms
   * </pre>
   *
   * <code>.google.protobuf.UInt64Value timeout = 5;</code>
   */
  com.google.protobuf.UInt64Value getTimeout();
  /**
   * <pre>
   * 全局事务超时时间, 单位ms
   * </pre>
   *
   * <code>.google.protobuf.UInt64Value timeout = 5;</code>
   */
  com.google.protobuf.UInt64ValueOrBuilder getTimeoutOrBuilder();

  /**
   * <code>string transName = 6;</code>
   */
  java.lang.String getTransName();
  /**
   * <code>string transName = 6;</code>
   */
  com.google.protobuf.ByteString
      getTransNameBytes();

  /**
   * <code>.google.protobuf.UInt32Value timeoutType = 7;</code>
   */
  boolean hasTimeoutType();
  /**
   * <code>.google.protobuf.UInt32Value timeoutType = 7;</code>
   */
  com.google.protobuf.UInt32Value getTimeoutType();
  /**
   * <code>.google.protobuf.UInt32Value timeoutType = 7;</code>
   */
  com.google.protobuf.UInt32ValueOrBuilder getTimeoutTypeOrBuilder();

  /**
   * <pre>
   *事务模型
   * </pre>
   *
   * <code>string transMode = 8;</code>
   */
  java.lang.String getTransMode();
  /**
   * <pre>
   *事务模型
   * </pre>
   *
   * <code>string transMode = 8;</code>
   */
  com.google.protobuf.ByteString
      getTransModeBytes();

  /**
   * <code>string transType = 9;</code>
   */
  java.lang.String getTransType();
  /**
   * <code>string transType = 9;</code>
   */
  com.google.protobuf.ByteString
      getTransTypeBytes();

  /**
   * <code>string callMode = 10;</code>
   */
  java.lang.String getCallMode();
  /**
   * <code>string callMode = 10;</code>
   */
  com.google.protobuf.ByteString
      getCallModeBytes();

  /**
   * <code>repeated .GlobalSagaTransRequest.BranchSagaTransDetail branchTransDetails = 12;</code>
   */
  java.util.List<com.ops.sc.rpc.dto.GlobalSagaTransRequest.BranchSagaTransDetail> 
      getBranchTransDetailsList();
  /**
   * <code>repeated .GlobalSagaTransRequest.BranchSagaTransDetail branchTransDetails = 12;</code>
   */
  com.ops.sc.rpc.dto.GlobalSagaTransRequest.BranchSagaTransDetail getBranchTransDetails(int index);
  /**
   * <code>repeated .GlobalSagaTransRequest.BranchSagaTransDetail branchTransDetails = 12;</code>
   */
  int getBranchTransDetailsCount();
  /**
   * <code>repeated .GlobalSagaTransRequest.BranchSagaTransDetail branchTransDetails = 12;</code>
   */
  java.util.List<? extends com.ops.sc.rpc.dto.GlobalSagaTransRequest.BranchSagaTransDetailOrBuilder> 
      getBranchTransDetailsOrBuilderList();
  /**
   * <code>repeated .GlobalSagaTransRequest.BranchSagaTransDetail branchTransDetails = 12;</code>
   */
  com.ops.sc.rpc.dto.GlobalSagaTransRequest.BranchSagaTransDetailOrBuilder getBranchTransDetailsOrBuilder(
      int index);
}
