// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: globalRequest.proto

package com.ops.sc.rpc.dto;

public interface GlobalTransRollbackResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GlobalTransRollbackResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ParentResponse baseResponse = 1;</code>
   */
  boolean hasBaseResponse();
  /**
   * <code>.ParentResponse baseResponse = 1;</code>
   */
  com.ops.sc.rpc.dto.ParentResponse getBaseResponse();
  /**
   * <code>.ParentResponse baseResponse = 1;</code>
   */
  com.ops.sc.rpc.dto.ParentResponseOrBuilder getBaseResponseOrBuilder();
}
