// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: globalRequest.proto

package com.ops.sc.rpc.dto;

public interface GlobalTransResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GlobalTransResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ParentResponse baseResponse = 1;</code>
   */
  boolean hasBaseResponse();
  /**
   * <code>.ParentResponse baseResponse = 1;</code>
   */
  com.ops.sc.rpc.dto.ParentResponse getBaseResponse();
  /**
   * <code>.ParentResponse baseResponse = 1;</code>
   */
  com.ops.sc.rpc.dto.ParentResponseOrBuilder getBaseResponseOrBuilder();

  /**
   * <code>string tid = 2;</code>
   */
  java.lang.String getTid();
  /**
   * <code>string tid = 2;</code>
   */
  com.google.protobuf.ByteString
      getTidBytes();

  /**
   * <code>.google.protobuf.UInt64Value checkBackMetaId = 3;</code>
   */
  boolean hasCheckBackMetaId();
  /**
   * <code>.google.protobuf.UInt64Value checkBackMetaId = 3;</code>
   */
  com.google.protobuf.UInt64Value getCheckBackMetaId();
  /**
   * <code>.google.protobuf.UInt64Value checkBackMetaId = 3;</code>
   */
  com.google.protobuf.UInt64ValueOrBuilder getCheckBackMetaIdOrBuilder();
}
