// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgTrans.proto

package com.ops.sc.rpc.dto;

public interface MQProducerRegRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MQProducerRegRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestId = 1;</code>
   */
  java.lang.String getRequestId();
  /**
   * <code>string requestId = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>.google.protobuf.UInt32Value type = 2;</code>
   */
  boolean hasType();
  /**
   * <code>.google.protobuf.UInt32Value type = 2;</code>
   */
  com.google.protobuf.UInt32Value getType();
  /**
   * <code>.google.protobuf.UInt32Value type = 2;</code>
   */
  com.google.protobuf.UInt32ValueOrBuilder getTypeOrBuilder();

  /**
   * <code>string config = 3;</code>
   */
  java.lang.String getConfig();
  /**
   * <code>string config = 3;</code>
   */
  com.google.protobuf.ByteString
      getConfigBytes();
}
