// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parentResponse.proto

package com.ops.sc.rpc.dto;

public interface ParentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ParentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string code = 2;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string businessId = 3;</code>
   */
  java.lang.String getBusinessId();
  /**
   * <code>string businessId = 3;</code>
   */
  com.google.protobuf.ByteString
      getBusinessIdBytes();
}
