// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parentResponse.proto

package com.ops.sc.rpc.dto;

public final class ParentResponseOuterClass {
  private ParentResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024parentResponse.proto\"C\n\016ParentResponse" +
      "\022\017\n\007message\030\001 \001(\t\022\014\n\004code\030\002 \001(\t\022\022\n\nbusin" +
      "essId\030\003 \001(\tB\035\n\022com.ops.sc.rpc.dtoP\001\242\002\004HL" +
      "WSb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ParentResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ParentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParentResponse_descriptor,
        new java.lang.String[] { "Message", "Code", "BusinessId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
