// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stateService.proto

package com.ops.sc.rpc.dto;

public final class StateService {
  private StateService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StateServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StateServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StateServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StateServiceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022stateService.proto\032\024parentResponse.pro" +
      "to\032\036google/protobuf/wrappers.proto\"H\n\023St" +
      "ateServiceRequest\022\013\n\003tid\030\001 \001(\t\022\020\n\010branch" +
      "Id\030\002 \001(\t\022\022\n\nbusinessId\030\003 \001(\t\"k\n\024StateSer" +
      "viceResponse\022%\n\014baseResponse\030\001 \001(\0132\017.Par" +
      "entResponse\022,\n\006status\030\002 \001(\0132\034.google.pro" +
      "tobuf.UInt32ValueB\035\n\022com.ops.sc.rpc.dtoP" +
      "\001\242\002\004HLWSb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ops.sc.rpc.dto.ParentResponseOuterClass.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_StateServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StateServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StateServiceRequest_descriptor,
        new java.lang.String[] { "Tid", "BranchId", "BusinessId", });
    internal_static_StateServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StateServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StateServiceResponse_descriptor,
        new java.lang.String[] { "BaseResponse", "Status", });
    com.ops.sc.rpc.dto.ParentResponseOuterClass.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
