// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transQueryRequest.proto

package com.ops.sc.rpc.dto;

public interface TransQueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TransQueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string businessId = 1;</code>
   */
  java.lang.String getBusinessId();
  /**
   * <code>string businessId = 1;</code>
   */
  com.google.protobuf.ByteString
      getBusinessIdBytes();
}
