// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgTransmitBody.proto

package com.ops.sc.rpc.dto;

/**
 * Protobuf type {@code TransMessage}
 */
public  final class TransMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TransMessage)
    TransMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransMessage.newBuilder() to construct.
  private TransMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransMessage() {
    requestId_ = "";
    tid_ = "";
    transCode_ = "";
    transName_ = "";
    transType_ = "";
    msgTime_ = "";
    multiTenancyId_ = "";
    callerIp_ = "";
    msgBody_ = "";
    extension_ = "";
    appName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TransMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            requestId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            tid_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            transCode_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            transName_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            transType_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            msgTime_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            multiTenancyId_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            callerIp_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            msgBody_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            extension_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            appName_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ops.sc.rpc.dto.MsgTransmitBody.internal_static_TransMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ops.sc.rpc.dto.MsgTransmitBody.internal_static_TransMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ops.sc.rpc.dto.TransMessage.class, com.ops.sc.rpc.dto.TransMessage.Builder.class);
  }

  public static final int REQUESTID_FIELD_NUMBER = 1;
  private volatile java.lang.Object requestId_;
  /**
   * <code>string requestId = 1;</code>
   */
  public java.lang.String getRequestId() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestId_ = s;
      return s;
    }
  }
  /**
   * <code>string requestId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TID_FIELD_NUMBER = 2;
  private volatile java.lang.Object tid_;
  /**
   * <pre>
   * 全局事务ID
   * </pre>
   *
   * <code>string tid = 2;</code>
   */
  public java.lang.String getTid() {
    java.lang.Object ref = tid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 全局事务ID
   * </pre>
   *
   * <code>string tid = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTidBytes() {
    java.lang.Object ref = tid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSCODE_FIELD_NUMBER = 3;
  private volatile java.lang.Object transCode_;
  /**
   * <pre>
   *交易码
   * </pre>
   *
   * <code>string transCode = 3;</code>
   */
  public java.lang.String getTransCode() {
    java.lang.Object ref = transCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *交易码
   * </pre>
   *
   * <code>string transCode = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTransCodeBytes() {
    java.lang.Object ref = transCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object transName_;
  /**
   * <pre>
   *交易名
   * </pre>
   *
   * <code>string transName = 4;</code>
   */
  public java.lang.String getTransName() {
    java.lang.Object ref = transName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *交易名
   * </pre>
   *
   * <code>string transName = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTransNameBytes() {
    java.lang.Object ref = transName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSTYPE_FIELD_NUMBER = 5;
  private volatile java.lang.Object transType_;
  /**
   * <pre>
   *交易类型
   * </pre>
   *
   * <code>string transType = 5;</code>
   */
  public java.lang.String getTransType() {
    java.lang.Object ref = transType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *交易类型
   * </pre>
   *
   * <code>string transType = 5;</code>
   */
  public com.google.protobuf.ByteString
      getTransTypeBytes() {
    java.lang.Object ref = transType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSGTIME_FIELD_NUMBER = 6;
  private volatile java.lang.Object msgTime_;
  /**
   * <code>string msgTime = 6;</code>
   */
  public java.lang.String getMsgTime() {
    java.lang.Object ref = msgTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgTime_ = s;
      return s;
    }
  }
  /**
   * <code>string msgTime = 6;</code>
   */
  public com.google.protobuf.ByteString
      getMsgTimeBytes() {
    java.lang.Object ref = msgTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MULTITENANCYID_FIELD_NUMBER = 7;
  private volatile java.lang.Object multiTenancyId_;
  /**
   * <pre>
   *多租户
   * </pre>
   *
   * <code>string multiTenancyId = 7;</code>
   */
  public java.lang.String getMultiTenancyId() {
    java.lang.Object ref = multiTenancyId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      multiTenancyId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *多租户
   * </pre>
   *
   * <code>string multiTenancyId = 7;</code>
   */
  public com.google.protobuf.ByteString
      getMultiTenancyIdBytes() {
    java.lang.Object ref = multiTenancyId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      multiTenancyId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CALLERIP_FIELD_NUMBER = 8;
  private volatile java.lang.Object callerIp_;
  /**
   * <pre>
   * 调用方本机ip
   * </pre>
   *
   * <code>string callerIp = 8;</code>
   */
  public java.lang.String getCallerIp() {
    java.lang.Object ref = callerIp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      callerIp_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 调用方本机ip
   * </pre>
   *
   * <code>string callerIp = 8;</code>
   */
  public com.google.protobuf.ByteString
      getCallerIpBytes() {
    java.lang.Object ref = callerIp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      callerIp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSGBODY_FIELD_NUMBER = 9;
  private volatile java.lang.Object msgBody_;
  /**
   * <pre>
   * 事务消息体(json)
   * </pre>
   *
   * <code>string msgBody = 9;</code>
   */
  public java.lang.String getMsgBody() {
    java.lang.Object ref = msgBody_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgBody_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 事务消息体(json)
   * </pre>
   *
   * <code>string msgBody = 9;</code>
   */
  public com.google.protobuf.ByteString
      getMsgBodyBytes() {
    java.lang.Object ref = msgBody_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgBody_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTENSION_FIELD_NUMBER = 10;
  private volatile java.lang.Object extension_;
  /**
   * <pre>
   * 统一JSON格式如{"exchange":xxx,"bindKey":xxx}，每次发送时用户指定
   * </pre>
   *
   * <code>string extension = 10;</code>
   */
  public java.lang.String getExtension() {
    java.lang.Object ref = extension_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extension_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 统一JSON格式如{"exchange":xxx,"bindKey":xxx}，每次发送时用户指定
   * </pre>
   *
   * <code>string extension = 10;</code>
   */
  public com.google.protobuf.ByteString
      getExtensionBytes() {
    java.lang.Object ref = extension_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extension_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPNAME_FIELD_NUMBER = 11;
  private volatile java.lang.Object appName_;
  /**
   * <pre>
   * 应用名称
   * </pre>
   *
   * <code>string appName = 11;</code>
   */
  public java.lang.String getAppName() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 应用名称
   * </pre>
   *
   * <code>string appName = 11;</code>
   */
  public com.google.protobuf.ByteString
      getAppNameBytes() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRequestIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
    }
    if (!getTidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tid_);
    }
    if (!getTransCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, transCode_);
    }
    if (!getTransNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, transName_);
    }
    if (!getTransTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, transType_);
    }
    if (!getMsgTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, msgTime_);
    }
    if (!getMultiTenancyIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, multiTenancyId_);
    }
    if (!getCallerIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, callerIp_);
    }
    if (!getMsgBodyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, msgBody_);
    }
    if (!getExtensionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, extension_);
    }
    if (!getAppNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, appName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRequestIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
    }
    if (!getTidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tid_);
    }
    if (!getTransCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, transCode_);
    }
    if (!getTransNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, transName_);
    }
    if (!getTransTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, transType_);
    }
    if (!getMsgTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, msgTime_);
    }
    if (!getMultiTenancyIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, multiTenancyId_);
    }
    if (!getCallerIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, callerIp_);
    }
    if (!getMsgBodyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, msgBody_);
    }
    if (!getExtensionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, extension_);
    }
    if (!getAppNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, appName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ops.sc.rpc.dto.TransMessage)) {
      return super.equals(obj);
    }
    com.ops.sc.rpc.dto.TransMessage other = (com.ops.sc.rpc.dto.TransMessage) obj;

    boolean result = true;
    result = result && getRequestId()
        .equals(other.getRequestId());
    result = result && getTid()
        .equals(other.getTid());
    result = result && getTransCode()
        .equals(other.getTransCode());
    result = result && getTransName()
        .equals(other.getTransName());
    result = result && getTransType()
        .equals(other.getTransType());
    result = result && getMsgTime()
        .equals(other.getMsgTime());
    result = result && getMultiTenancyId()
        .equals(other.getMultiTenancyId());
    result = result && getCallerIp()
        .equals(other.getCallerIp());
    result = result && getMsgBody()
        .equals(other.getMsgBody());
    result = result && getExtension()
        .equals(other.getExtension());
    result = result && getAppName()
        .equals(other.getAppName());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId().hashCode();
    hash = (37 * hash) + TID_FIELD_NUMBER;
    hash = (53 * hash) + getTid().hashCode();
    hash = (37 * hash) + TRANSCODE_FIELD_NUMBER;
    hash = (53 * hash) + getTransCode().hashCode();
    hash = (37 * hash) + TRANSNAME_FIELD_NUMBER;
    hash = (53 * hash) + getTransName().hashCode();
    hash = (37 * hash) + TRANSTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getTransType().hashCode();
    hash = (37 * hash) + MSGTIME_FIELD_NUMBER;
    hash = (53 * hash) + getMsgTime().hashCode();
    hash = (37 * hash) + MULTITENANCYID_FIELD_NUMBER;
    hash = (53 * hash) + getMultiTenancyId().hashCode();
    hash = (37 * hash) + CALLERIP_FIELD_NUMBER;
    hash = (53 * hash) + getCallerIp().hashCode();
    hash = (37 * hash) + MSGBODY_FIELD_NUMBER;
    hash = (53 * hash) + getMsgBody().hashCode();
    hash = (37 * hash) + EXTENSION_FIELD_NUMBER;
    hash = (53 * hash) + getExtension().hashCode();
    hash = (37 * hash) + APPNAME_FIELD_NUMBER;
    hash = (53 * hash) + getAppName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ops.sc.rpc.dto.TransMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ops.sc.rpc.dto.TransMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ops.sc.rpc.dto.TransMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ops.sc.rpc.dto.TransMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ops.sc.rpc.dto.TransMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ops.sc.rpc.dto.TransMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ops.sc.rpc.dto.TransMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ops.sc.rpc.dto.TransMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ops.sc.rpc.dto.TransMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ops.sc.rpc.dto.TransMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ops.sc.rpc.dto.TransMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ops.sc.rpc.dto.TransMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ops.sc.rpc.dto.TransMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TransMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TransMessage)
      com.ops.sc.rpc.dto.TransMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ops.sc.rpc.dto.MsgTransmitBody.internal_static_TransMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ops.sc.rpc.dto.MsgTransmitBody.internal_static_TransMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ops.sc.rpc.dto.TransMessage.class, com.ops.sc.rpc.dto.TransMessage.Builder.class);
    }

    // Construct using com.ops.sc.rpc.dto.TransMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestId_ = "";

      tid_ = "";

      transCode_ = "";

      transName_ = "";

      transType_ = "";

      msgTime_ = "";

      multiTenancyId_ = "";

      callerIp_ = "";

      msgBody_ = "";

      extension_ = "";

      appName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ops.sc.rpc.dto.MsgTransmitBody.internal_static_TransMessage_descriptor;
    }

    @java.lang.Override
    public com.ops.sc.rpc.dto.TransMessage getDefaultInstanceForType() {
      return com.ops.sc.rpc.dto.TransMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.ops.sc.rpc.dto.TransMessage build() {
      com.ops.sc.rpc.dto.TransMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ops.sc.rpc.dto.TransMessage buildPartial() {
      com.ops.sc.rpc.dto.TransMessage result = new com.ops.sc.rpc.dto.TransMessage(this);
      result.requestId_ = requestId_;
      result.tid_ = tid_;
      result.transCode_ = transCode_;
      result.transName_ = transName_;
      result.transType_ = transType_;
      result.msgTime_ = msgTime_;
      result.multiTenancyId_ = multiTenancyId_;
      result.callerIp_ = callerIp_;
      result.msgBody_ = msgBody_;
      result.extension_ = extension_;
      result.appName_ = appName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ops.sc.rpc.dto.TransMessage) {
        return mergeFrom((com.ops.sc.rpc.dto.TransMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ops.sc.rpc.dto.TransMessage other) {
      if (other == com.ops.sc.rpc.dto.TransMessage.getDefaultInstance()) return this;
      if (!other.getRequestId().isEmpty()) {
        requestId_ = other.requestId_;
        onChanged();
      }
      if (!other.getTid().isEmpty()) {
        tid_ = other.tid_;
        onChanged();
      }
      if (!other.getTransCode().isEmpty()) {
        transCode_ = other.transCode_;
        onChanged();
      }
      if (!other.getTransName().isEmpty()) {
        transName_ = other.transName_;
        onChanged();
      }
      if (!other.getTransType().isEmpty()) {
        transType_ = other.transType_;
        onChanged();
      }
      if (!other.getMsgTime().isEmpty()) {
        msgTime_ = other.msgTime_;
        onChanged();
      }
      if (!other.getMultiTenancyId().isEmpty()) {
        multiTenancyId_ = other.multiTenancyId_;
        onChanged();
      }
      if (!other.getCallerIp().isEmpty()) {
        callerIp_ = other.callerIp_;
        onChanged();
      }
      if (!other.getMsgBody().isEmpty()) {
        msgBody_ = other.msgBody_;
        onChanged();
      }
      if (!other.getExtension().isEmpty()) {
        extension_ = other.extension_;
        onChanged();
      }
      if (!other.getAppName().isEmpty()) {
        appName_ = other.appName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ops.sc.rpc.dto.TransMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ops.sc.rpc.dto.TransMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object requestId_ = "";
    /**
     * <code>string requestId = 1;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string requestId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string requestId = 1;</code>
     */
    public Builder setRequestId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string requestId = 1;</code>
     */
    public Builder clearRequestId() {
      
      requestId_ = getDefaultInstance().getRequestId();
      onChanged();
      return this;
    }
    /**
     * <code>string requestId = 1;</code>
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tid_ = "";
    /**
     * <pre>
     * 全局事务ID
     * </pre>
     *
     * <code>string tid = 2;</code>
     */
    public java.lang.String getTid() {
      java.lang.Object ref = tid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 全局事务ID
     * </pre>
     *
     * <code>string tid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTidBytes() {
      java.lang.Object ref = tid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 全局事务ID
     * </pre>
     *
     * <code>string tid = 2;</code>
     */
    public Builder setTid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 全局事务ID
     * </pre>
     *
     * <code>string tid = 2;</code>
     */
    public Builder clearTid() {
      
      tid_ = getDefaultInstance().getTid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 全局事务ID
     * </pre>
     *
     * <code>string tid = 2;</code>
     */
    public Builder setTidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object transCode_ = "";
    /**
     * <pre>
     *交易码
     * </pre>
     *
     * <code>string transCode = 3;</code>
     */
    public java.lang.String getTransCode() {
      java.lang.Object ref = transCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *交易码
     * </pre>
     *
     * <code>string transCode = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTransCodeBytes() {
      java.lang.Object ref = transCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *交易码
     * </pre>
     *
     * <code>string transCode = 3;</code>
     */
    public Builder setTransCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *交易码
     * </pre>
     *
     * <code>string transCode = 3;</code>
     */
    public Builder clearTransCode() {
      
      transCode_ = getDefaultInstance().getTransCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *交易码
     * </pre>
     *
     * <code>string transCode = 3;</code>
     */
    public Builder setTransCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object transName_ = "";
    /**
     * <pre>
     *交易名
     * </pre>
     *
     * <code>string transName = 4;</code>
     */
    public java.lang.String getTransName() {
      java.lang.Object ref = transName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *交易名
     * </pre>
     *
     * <code>string transName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTransNameBytes() {
      java.lang.Object ref = transName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *交易名
     * </pre>
     *
     * <code>string transName = 4;</code>
     */
    public Builder setTransName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *交易名
     * </pre>
     *
     * <code>string transName = 4;</code>
     */
    public Builder clearTransName() {
      
      transName_ = getDefaultInstance().getTransName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *交易名
     * </pre>
     *
     * <code>string transName = 4;</code>
     */
    public Builder setTransNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object transType_ = "";
    /**
     * <pre>
     *交易类型
     * </pre>
     *
     * <code>string transType = 5;</code>
     */
    public java.lang.String getTransType() {
      java.lang.Object ref = transType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *交易类型
     * </pre>
     *
     * <code>string transType = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTransTypeBytes() {
      java.lang.Object ref = transType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *交易类型
     * </pre>
     *
     * <code>string transType = 5;</code>
     */
    public Builder setTransType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *交易类型
     * </pre>
     *
     * <code>string transType = 5;</code>
     */
    public Builder clearTransType() {
      
      transType_ = getDefaultInstance().getTransType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *交易类型
     * </pre>
     *
     * <code>string transType = 5;</code>
     */
    public Builder setTransTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object msgTime_ = "";
    /**
     * <code>string msgTime = 6;</code>
     */
    public java.lang.String getMsgTime() {
      java.lang.Object ref = msgTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msgTime = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMsgTimeBytes() {
      java.lang.Object ref = msgTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msgTime = 6;</code>
     */
    public Builder setMsgTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string msgTime = 6;</code>
     */
    public Builder clearMsgTime() {
      
      msgTime_ = getDefaultInstance().getMsgTime();
      onChanged();
      return this;
    }
    /**
     * <code>string msgTime = 6;</code>
     */
    public Builder setMsgTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msgTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object multiTenancyId_ = "";
    /**
     * <pre>
     *多租户
     * </pre>
     *
     * <code>string multiTenancyId = 7;</code>
     */
    public java.lang.String getMultiTenancyId() {
      java.lang.Object ref = multiTenancyId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        multiTenancyId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *多租户
     * </pre>
     *
     * <code>string multiTenancyId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMultiTenancyIdBytes() {
      java.lang.Object ref = multiTenancyId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        multiTenancyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *多租户
     * </pre>
     *
     * <code>string multiTenancyId = 7;</code>
     */
    public Builder setMultiTenancyId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      multiTenancyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *多租户
     * </pre>
     *
     * <code>string multiTenancyId = 7;</code>
     */
    public Builder clearMultiTenancyId() {
      
      multiTenancyId_ = getDefaultInstance().getMultiTenancyId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *多租户
     * </pre>
     *
     * <code>string multiTenancyId = 7;</code>
     */
    public Builder setMultiTenancyIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      multiTenancyId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object callerIp_ = "";
    /**
     * <pre>
     * 调用方本机ip
     * </pre>
     *
     * <code>string callerIp = 8;</code>
     */
    public java.lang.String getCallerIp() {
      java.lang.Object ref = callerIp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        callerIp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 调用方本机ip
     * </pre>
     *
     * <code>string callerIp = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCallerIpBytes() {
      java.lang.Object ref = callerIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        callerIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 调用方本机ip
     * </pre>
     *
     * <code>string callerIp = 8;</code>
     */
    public Builder setCallerIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      callerIp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 调用方本机ip
     * </pre>
     *
     * <code>string callerIp = 8;</code>
     */
    public Builder clearCallerIp() {
      
      callerIp_ = getDefaultInstance().getCallerIp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 调用方本机ip
     * </pre>
     *
     * <code>string callerIp = 8;</code>
     */
    public Builder setCallerIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      callerIp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object msgBody_ = "";
    /**
     * <pre>
     * 事务消息体(json)
     * </pre>
     *
     * <code>string msgBody = 9;</code>
     */
    public java.lang.String getMsgBody() {
      java.lang.Object ref = msgBody_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgBody_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 事务消息体(json)
     * </pre>
     *
     * <code>string msgBody = 9;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBodyBytes() {
      java.lang.Object ref = msgBody_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 事务消息体(json)
     * </pre>
     *
     * <code>string msgBody = 9;</code>
     */
    public Builder setMsgBody(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgBody_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事务消息体(json)
     * </pre>
     *
     * <code>string msgBody = 9;</code>
     */
    public Builder clearMsgBody() {
      
      msgBody_ = getDefaultInstance().getMsgBody();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事务消息体(json)
     * </pre>
     *
     * <code>string msgBody = 9;</code>
     */
    public Builder setMsgBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msgBody_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object extension_ = "";
    /**
     * <pre>
     * 统一JSON格式如{"exchange":xxx,"bindKey":xxx}，每次发送时用户指定
     * </pre>
     *
     * <code>string extension = 10;</code>
     */
    public java.lang.String getExtension() {
      java.lang.Object ref = extension_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extension_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 统一JSON格式如{"exchange":xxx,"bindKey":xxx}，每次发送时用户指定
     * </pre>
     *
     * <code>string extension = 10;</code>
     */
    public com.google.protobuf.ByteString
        getExtensionBytes() {
      java.lang.Object ref = extension_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extension_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 统一JSON格式如{"exchange":xxx,"bindKey":xxx}，每次发送时用户指定
     * </pre>
     *
     * <code>string extension = 10;</code>
     */
    public Builder setExtension(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extension_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 统一JSON格式如{"exchange":xxx,"bindKey":xxx}，每次发送时用户指定
     * </pre>
     *
     * <code>string extension = 10;</code>
     */
    public Builder clearExtension() {
      
      extension_ = getDefaultInstance().getExtension();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 统一JSON格式如{"exchange":xxx,"bindKey":xxx}，每次发送时用户指定
     * </pre>
     *
     * <code>string extension = 10;</code>
     */
    public Builder setExtensionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extension_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object appName_ = "";
    /**
     * <pre>
     * 应用名称
     * </pre>
     *
     * <code>string appName = 11;</code>
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 应用名称
     * </pre>
     *
     * <code>string appName = 11;</code>
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 应用名称
     * </pre>
     *
     * <code>string appName = 11;</code>
     */
    public Builder setAppName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 应用名称
     * </pre>
     *
     * <code>string appName = 11;</code>
     */
    public Builder clearAppName() {
      
      appName_ = getDefaultInstance().getAppName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 应用名称
     * </pre>
     *
     * <code>string appName = 11;</code>
     */
    public Builder setAppNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TransMessage)
  }

  // @@protoc_insertion_point(class_scope:TransMessage)
  private static final com.ops.sc.rpc.dto.TransMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ops.sc.rpc.dto.TransMessage();
  }

  public static com.ops.sc.rpc.dto.TransMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransMessage>
      PARSER = new com.google.protobuf.AbstractParser<TransMessage>() {
    @java.lang.Override
    public TransMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TransMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TransMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ops.sc.rpc.dto.TransMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

