// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transQueryRequest.proto

package com.ops.sc.rpc.dto;

public final class TransQueryRequestOuterClass {
  private TransQueryRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransQueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransQueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransQueryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransQueryResponse_BranchTransResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransQueryResponse_BranchTransResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransQueryResponse_BranchTransResponse_BranchParamEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransQueryResponse_BranchTransResponse_BranchParamEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransQueryResponse_BranchTransResponse_ExternalParamEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransQueryResponse_BranchTransResponse_ExternalParamEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransQueryResponse_BranchTransResponse_RollbackParamEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransQueryResponse_BranchTransResponse_RollbackParamEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027transQueryRequest.proto\032\024parentRespons" +
      "e.proto\032\036google/protobuf/wrappers.proto\"" +
      "\'\n\021TransQueryRequest\022\022\n\nbusinessId\030\001 \001(\t" +
      "\"\357\n\n\022TransQueryResponse\022%\n\014baseResponse\030" +
      "\001 \001(\0132\017.ParentResponse\022\022\n\nbusinessId\030\002 \001" +
      "(\t\022\013\n\003tid\030\003 \001(\t\022\024\n\014transGroupId\030\004 \001(\t\022\020\n" +
      "\010callerIp\030\005 \001(\t\022\017\n\007appName\030\006 \001(\t\022-\n\007time" +
      "out\030\007 \001(\0132\034.google.protobuf.UInt64Value\022" +
      "6\n\020callbackStrategy\030\010 \001(\0132\034.google.proto" +
      "buf.UInt32Value\0221\n\013timeoutType\030\t \001(\0132\034.g" +
      "oogle.protobuf.UInt32Value\022\021\n\ttransMode\030" +
      "\n \001(\t\022\022\n\ndataSource\030\013 \001(\t\0224\n\016callInParal" +
      "lel\030\014 \001(\0132\034.google.protobuf.UInt32Value\022" +
      "\024\n\014rollbackInfo\030\r \001(\t\022\021\n\ttransType\030\016 \001(\t" +
      "\022\020\n\010callMode\030\017 \001(\t\022\016\n\006status\030\020 \001(\t\022\023\n\013cr" +
      "eate_time\030\021 \001(\t\022\020\n\010end_time\030\022 \001(\t\022C\n\022bra" +
      "nchTransDetails\030\023 \003(\0132\'.TransQueryRespon" +
      "se.BranchTransResponse\032\251\006\n\023BranchTransRe" +
      "sponse\022\013\n\003bid\030\001 \001(\t\022\025\n\rbranchAppName\030\002 \001" +
      "(\t\022\022\n\nbranchName\030\003 \001(\t\022\027\n\017transactionNam" +
      "e\030\004 \001(\t\022\013\n\003url\030\005 \001(\t\022\024\n\014commitMethod\030\006 \001" +
      "(\t\022\026\n\016rollbackMethod\030\007 \001(\t\022M\n\013branchPara" +
      "m\030\010 \003(\01328.TransQueryResponse.BranchTrans" +
      "Response.BranchParamEntry\022Q\n\rexternalPar" +
      "am\030\t \003(\0132:.TransQueryResponse.BranchTran" +
      "sResponse.ExternalParamEntry\022\021\n\thasParen" +
      "t\030\n \001(\010\022\031\n\021parentBranchNames\030\013 \003(\t\022-\n\007ti" +
      "meout\030\014 \001(\0132\034.google.protobuf.UInt64Valu" +
      "e\0221\n\013timeOutType\030\r \001(\0132\034.google.protobuf" +
      ".UInt32Value\022\025\n\rretryRequired\030\016 \001(\010\022Q\n\rr" +
      "ollbackParam\030\017 \003(\0132:.TransQueryResponse." +
      "BranchTransResponse.RollbackParamEntry\022\023" +
      "\n\013returnParam\030\020 \003(\t\022\016\n\006status\030\021 \001(\t\022\023\n\013c" +
      "reate_time\030\022 \001(\t\022\020\n\010end_time\030\023 \001(\t\0322\n\020Br" +
      "anchParamEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001" +
      "(\t:\0028\001\0324\n\022ExternalParamEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\r\n\005value\030\002 \001(\t:\0028\001\0324\n\022RollbackParamEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\035\n\022co" +
      "m.ops.sc.rpc.dtoP\001\242\002\004HLWSb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ops.sc.rpc.dto.ParentResponseOuterClass.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_TransQueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransQueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransQueryRequest_descriptor,
        new java.lang.String[] { "BusinessId", });
    internal_static_TransQueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TransQueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransQueryResponse_descriptor,
        new java.lang.String[] { "BaseResponse", "BusinessId", "Tid", "TransGroupId", "CallerIp", "AppName", "Timeout", "CallbackStrategy", "TimeoutType", "TransMode", "DataSource", "CallInParallel", "RollbackInfo", "TransType", "CallMode", "Status", "CreateTime", "EndTime", "BranchTransDetails", });
    internal_static_TransQueryResponse_BranchTransResponse_descriptor =
      internal_static_TransQueryResponse_descriptor.getNestedTypes().get(0);
    internal_static_TransQueryResponse_BranchTransResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransQueryResponse_BranchTransResponse_descriptor,
        new java.lang.String[] { "Bid", "BranchAppName", "BranchName", "TransactionName", "Url", "CommitMethod", "RollbackMethod", "BranchParam", "ExternalParam", "HasParent", "ParentBranchNames", "Timeout", "TimeOutType", "RetryRequired", "RollbackParam", "ReturnParam", "Status", "CreateTime", "EndTime", });
    internal_static_TransQueryResponse_BranchTransResponse_BranchParamEntry_descriptor =
      internal_static_TransQueryResponse_BranchTransResponse_descriptor.getNestedTypes().get(0);
    internal_static_TransQueryResponse_BranchTransResponse_BranchParamEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransQueryResponse_BranchTransResponse_BranchParamEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_TransQueryResponse_BranchTransResponse_ExternalParamEntry_descriptor =
      internal_static_TransQueryResponse_BranchTransResponse_descriptor.getNestedTypes().get(1);
    internal_static_TransQueryResponse_BranchTransResponse_ExternalParamEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransQueryResponse_BranchTransResponse_ExternalParamEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_TransQueryResponse_BranchTransResponse_RollbackParamEntry_descriptor =
      internal_static_TransQueryResponse_BranchTransResponse_descriptor.getNestedTypes().get(2);
    internal_static_TransQueryResponse_BranchTransResponse_RollbackParamEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransQueryResponse_BranchTransResponse_RollbackParamEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.ops.sc.rpc.dto.ParentResponseOuterClass.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
