// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transCompensationRequest.proto

package com.ops.sc.rpc.dto;

public interface TransCompensationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TransCompensationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string businessId = 1;</code>
   */
  java.lang.String getBusinessId();
  /**
   * <code>string businessId = 1;</code>
   */
  com.google.protobuf.ByteString
      getBusinessIdBytes();

  /**
   * <code>string tid = 2;</code>
   */
  java.lang.String getTid();
  /**
   * <code>string tid = 2;</code>
   */
  com.google.protobuf.ByteString
      getTidBytes();

  /**
   * <pre>
   * 调用方本机ip
   * </pre>
   *
   * <code>string callerIp = 3;</code>
   */
  java.lang.String getCallerIp();
  /**
   * <pre>
   * 调用方本机ip
   * </pre>
   *
   * <code>string callerIp = 3;</code>
   */
  com.google.protobuf.ByteString
      getCallerIpBytes();

  /**
   * <pre>
   * 应用名称
   * </pre>
   *
   * <code>string appName = 4;</code>
   */
  java.lang.String getAppName();
  /**
   * <pre>
   * 应用名称
   * </pre>
   *
   * <code>string appName = 4;</code>
   */
  com.google.protobuf.ByteString
      getAppNameBytes();
}
