// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transCompensationRequest.proto

package com.ops.sc.rpc.dto;

public final class TransCompensationRequestOuterClass {
  private TransCompensationRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransCompensationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransCompensationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransCompensationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransCompensationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036transCompensationRequest.proto\032\024parent" +
      "Response.proto\032\036google/protobuf/wrappers" +
      ".proto\"^\n\030TransCompensationRequest\022\022\n\nbu" +
      "sinessId\030\001 \001(\t\022\013\n\003tid\030\002 \001(\t\022\020\n\010callerIp\030" +
      "\003 \001(\t\022\017\n\007appName\030\004 \001(\t\"c\n\031TransCompensat" +
      "ionResponse\022%\n\014baseResponse\030\001 \001(\0132\017.Pare" +
      "ntResponse\022\013\n\003tid\030\002 \001(\t\022\022\n\nbusinessId\030\003 " +
      "\001(\tB\035\n\022com.ops.sc.rpc.dtoP\001\242\002\004HLWSb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ops.sc.rpc.dto.ParentResponseOuterClass.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_TransCompensationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransCompensationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransCompensationRequest_descriptor,
        new java.lang.String[] { "BusinessId", "Tid", "CallerIp", "AppName", });
    internal_static_TransCompensationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TransCompensationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransCompensationResponse_descriptor,
        new java.lang.String[] { "BaseResponse", "Tid", "BusinessId", });
    com.ops.sc.rpc.dto.ParentResponseOuterClass.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
