// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transCompensationRequest.proto

package com.ops.sc.rpc.dto;

public interface TransCompensationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TransCompensationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ParentResponse baseResponse = 1;</code>
   */
  boolean hasBaseResponse();
  /**
   * <code>.ParentResponse baseResponse = 1;</code>
   */
  com.ops.sc.rpc.dto.ParentResponse getBaseResponse();
  /**
   * <code>.ParentResponse baseResponse = 1;</code>
   */
  com.ops.sc.rpc.dto.ParentResponseOrBuilder getBaseResponseOrBuilder();

  /**
   * <code>string tid = 2;</code>
   */
  java.lang.String getTid();
  /**
   * <code>string tid = 2;</code>
   */
  com.google.protobuf.ByteString
      getTidBytes();

  /**
   * <code>string businessId = 3;</code>
   */
  java.lang.String getBusinessId();
  /**
   * <code>string businessId = 3;</code>
   */
  com.google.protobuf.ByteString
      getBusinessIdBytes();
}
