// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: callbackService.proto

package com.ops.sc.rpc.grpc.callback;

/**
 * Protobuf type {@code RpcCallBackResponse}
 */
public  final class RpcCallBackResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RpcCallBackResponse)
    RpcCallBackResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RpcCallBackResponse.newBuilder() to construct.
  private RpcCallBackResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RpcCallBackResponse() {
    callBackType_ = 0;
    branchType_ = 0;
    tid_ = "";
    branchId_ = "";
    dataSource_ = "";
    callBackInterface_ = "";
    callbackMethod_ = "";
    params_ = com.google.protobuf.ByteString.EMPTY;
    requestId_ = "";
    registerResult_ = false;
    heartBeatResult_ = false;
    appName_ = "";
    resourceId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RpcCallBackResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            callBackType_ = input.readInt32();
            break;
          }
          case 16: {

            branchType_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            tid_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            branchId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            dataSource_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            callBackInterface_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            callbackMethod_ = s;
            break;
          }
          case 66: {

            params_ = input.readBytes();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            requestId_ = s;
            break;
          }
          case 80: {

            registerResult_ = input.readBool();
            break;
          }
          case 88: {

            heartBeatResult_ = input.readBool();
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            appName_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            resourceId_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ops.sc.rpc.grpc.callback.CallbackServiceProto.internal_static_RpcCallBackResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ops.sc.rpc.grpc.callback.CallbackServiceProto.internal_static_RpcCallBackResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ops.sc.rpc.grpc.callback.RpcCallBackResponse.class, com.ops.sc.rpc.grpc.callback.RpcCallBackResponse.Builder.class);
  }

  public static final int CALLBACKTYPE_FIELD_NUMBER = 1;
  private int callBackType_;
  /**
   * <pre>
   * commit还是rollBack
   * </pre>
   *
   * <code>int32 callBackType = 1;</code>
   */
  public int getCallBackType() {
    return callBackType_;
  }

  public static final int BRANCHTYPE_FIELD_NUMBER = 2;
  private int branchType_;
  /**
   * <pre>
   * 分支类型
   * </pre>
   *
   * <code>int32 branchType = 2;</code>
   */
  public int getBranchType() {
    return branchType_;
  }

  public static final int TID_FIELD_NUMBER = 3;
  private volatile java.lang.Object tid_;
  /**
   * <pre>
   * 全局事务id
   * </pre>
   *
   * <code>string tid = 3;</code>
   */
  public java.lang.String getTid() {
    java.lang.Object ref = tid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 全局事务id
   * </pre>
   *
   * <code>string tid = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTidBytes() {
    java.lang.Object ref = tid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BRANCHID_FIELD_NUMBER = 4;
  private volatile java.lang.Object branchId_;
  /**
   * <pre>
   * 分支事务id
   * </pre>
   *
   * <code>string branchId = 4;</code>
   */
  public java.lang.String getBranchId() {
    java.lang.Object ref = branchId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      branchId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 分支事务id
   * </pre>
   *
   * <code>string branchId = 4;</code>
   */
  public com.google.protobuf.ByteString
      getBranchIdBytes() {
    java.lang.Object ref = branchId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      branchId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATASOURCE_FIELD_NUMBER = 5;
  private volatile java.lang.Object dataSource_;
  /**
   * <pre>
   *数据源，用于多数据源场景
   * </pre>
   *
   * <code>string dataSource = 5;</code>
   */
  public java.lang.String getDataSource() {
    java.lang.Object ref = dataSource_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataSource_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *数据源，用于多数据源场景
   * </pre>
   *
   * <code>string dataSource = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDataSourceBytes() {
    java.lang.Object ref = dataSource_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataSource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CALLBACKINTERFACE_FIELD_NUMBER = 6;
  private volatile java.lang.Object callBackInterface_;
  /**
   * <pre>
   *回调接口
   * </pre>
   *
   * <code>string callBackInterface = 6;</code>
   */
  public java.lang.String getCallBackInterface() {
    java.lang.Object ref = callBackInterface_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      callBackInterface_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *回调接口
   * </pre>
   *
   * <code>string callBackInterface = 6;</code>
   */
  public com.google.protobuf.ByteString
      getCallBackInterfaceBytes() {
    java.lang.Object ref = callBackInterface_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      callBackInterface_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CALLBACKMETHOD_FIELD_NUMBER = 7;
  private volatile java.lang.Object callbackMethod_;
  /**
   * <pre>
   *回调方法
   * </pre>
   *
   * <code>string callbackMethod = 7;</code>
   */
  public java.lang.String getCallbackMethod() {
    java.lang.Object ref = callbackMethod_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      callbackMethod_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *回调方法
   * </pre>
   *
   * <code>string callbackMethod = 7;</code>
   */
  public com.google.protobuf.ByteString
      getCallbackMethodBytes() {
    java.lang.Object ref = callbackMethod_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      callbackMethod_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAMS_FIELD_NUMBER = 8;
  private com.google.protobuf.ByteString params_;
  /**
   * <pre>
   *事务消息producerName以及TCC模式的参数
   * </pre>
   *
   * <code>bytes params = 8;</code>
   */
  public com.google.protobuf.ByteString getParams() {
    return params_;
  }

  public static final int REQUESTID_FIELD_NUMBER = 9;
  private volatile java.lang.Object requestId_;
  /**
   * <pre>
   * 请求唯一标识
   * </pre>
   *
   * <code>string requestId = 9;</code>
   */
  public java.lang.String getRequestId() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 请求唯一标识
   * </pre>
   *
   * <code>string requestId = 9;</code>
   */
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REGISTERRESULT_FIELD_NUMBER = 10;
  private boolean registerResult_;
  /**
   * <pre>
   *注册成功标识
   * </pre>
   *
   * <code>bool registerResult = 10;</code>
   */
  public boolean getRegisterResult() {
    return registerResult_;
  }

  public static final int HEARTBEATRESULT_FIELD_NUMBER = 11;
  private boolean heartBeatResult_;
  /**
   * <pre>
   *心跳返回
   * </pre>
   *
   * <code>bool heartBeatResult = 11;</code>
   */
  public boolean getHeartBeatResult() {
    return heartBeatResult_;
  }

  public static final int APPNAME_FIELD_NUMBER = 12;
  private volatile java.lang.Object appName_;
  /**
   * <pre>
   *客户端唯一appName标识
   * </pre>
   *
   * <code>string appName = 12;</code>
   */
  public java.lang.String getAppName() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *客户端唯一appName标识
   * </pre>
   *
   * <code>string appName = 12;</code>
   */
  public com.google.protobuf.ByteString
      getAppNameBytes() {
    java.lang.Object ref = appName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESOURCEID_FIELD_NUMBER = 13;
  private volatile java.lang.Object resourceId_;
  /**
   * <code>string resourceId = 13;</code>
   */
  public java.lang.String getResourceId() {
    java.lang.Object ref = resourceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resourceId_ = s;
      return s;
    }
  }
  /**
   * <code>string resourceId = 13;</code>
   */
  public com.google.protobuf.ByteString
      getResourceIdBytes() {
    java.lang.Object ref = resourceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resourceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (callBackType_ != 0) {
      output.writeInt32(1, callBackType_);
    }
    if (branchType_ != 0) {
      output.writeInt32(2, branchType_);
    }
    if (!getTidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tid_);
    }
    if (!getBranchIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, branchId_);
    }
    if (!getDataSourceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dataSource_);
    }
    if (!getCallBackInterfaceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, callBackInterface_);
    }
    if (!getCallbackMethodBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, callbackMethod_);
    }
    if (!params_.isEmpty()) {
      output.writeBytes(8, params_);
    }
    if (!getRequestIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, requestId_);
    }
    if (registerResult_ != false) {
      output.writeBool(10, registerResult_);
    }
    if (heartBeatResult_ != false) {
      output.writeBool(11, heartBeatResult_);
    }
    if (!getAppNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, appName_);
    }
    if (!getResourceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, resourceId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (callBackType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, callBackType_);
    }
    if (branchType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, branchType_);
    }
    if (!getTidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tid_);
    }
    if (!getBranchIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, branchId_);
    }
    if (!getDataSourceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dataSource_);
    }
    if (!getCallBackInterfaceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, callBackInterface_);
    }
    if (!getCallbackMethodBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, callbackMethod_);
    }
    if (!params_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, params_);
    }
    if (!getRequestIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, requestId_);
    }
    if (registerResult_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, registerResult_);
    }
    if (heartBeatResult_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, heartBeatResult_);
    }
    if (!getAppNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, appName_);
    }
    if (!getResourceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, resourceId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ops.sc.rpc.grpc.callback.RpcCallBackResponse)) {
      return super.equals(obj);
    }
    com.ops.sc.rpc.grpc.callback.RpcCallBackResponse other = (com.ops.sc.rpc.grpc.callback.RpcCallBackResponse) obj;

    boolean result = true;
    result = result && (getCallBackType()
        == other.getCallBackType());
    result = result && (getBranchType()
        == other.getBranchType());
    result = result && getTid()
        .equals(other.getTid());
    result = result && getBranchId()
        .equals(other.getBranchId());
    result = result && getDataSource()
        .equals(other.getDataSource());
    result = result && getCallBackInterface()
        .equals(other.getCallBackInterface());
    result = result && getCallbackMethod()
        .equals(other.getCallbackMethod());
    result = result && getParams()
        .equals(other.getParams());
    result = result && getRequestId()
        .equals(other.getRequestId());
    result = result && (getRegisterResult()
        == other.getRegisterResult());
    result = result && (getHeartBeatResult()
        == other.getHeartBeatResult());
    result = result && getAppName()
        .equals(other.getAppName());
    result = result && getResourceId()
        .equals(other.getResourceId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CALLBACKTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getCallBackType();
    hash = (37 * hash) + BRANCHTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getBranchType();
    hash = (37 * hash) + TID_FIELD_NUMBER;
    hash = (53 * hash) + getTid().hashCode();
    hash = (37 * hash) + BRANCHID_FIELD_NUMBER;
    hash = (53 * hash) + getBranchId().hashCode();
    hash = (37 * hash) + DATASOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getDataSource().hashCode();
    hash = (37 * hash) + CALLBACKINTERFACE_FIELD_NUMBER;
    hash = (53 * hash) + getCallBackInterface().hashCode();
    hash = (37 * hash) + CALLBACKMETHOD_FIELD_NUMBER;
    hash = (53 * hash) + getCallbackMethod().hashCode();
    hash = (37 * hash) + PARAMS_FIELD_NUMBER;
    hash = (53 * hash) + getParams().hashCode();
    hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId().hashCode();
    hash = (37 * hash) + REGISTERRESULT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRegisterResult());
    hash = (37 * hash) + HEARTBEATRESULT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHeartBeatResult());
    hash = (37 * hash) + APPNAME_FIELD_NUMBER;
    hash = (53 * hash) + getAppName().hashCode();
    hash = (37 * hash) + RESOURCEID_FIELD_NUMBER;
    hash = (53 * hash) + getResourceId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ops.sc.rpc.grpc.callback.RpcCallBackResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ops.sc.rpc.grpc.callback.RpcCallBackResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ops.sc.rpc.grpc.callback.RpcCallBackResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ops.sc.rpc.grpc.callback.RpcCallBackResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ops.sc.rpc.grpc.callback.RpcCallBackResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ops.sc.rpc.grpc.callback.RpcCallBackResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ops.sc.rpc.grpc.callback.RpcCallBackResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ops.sc.rpc.grpc.callback.RpcCallBackResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ops.sc.rpc.grpc.callback.RpcCallBackResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ops.sc.rpc.grpc.callback.RpcCallBackResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ops.sc.rpc.grpc.callback.RpcCallBackResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ops.sc.rpc.grpc.callback.RpcCallBackResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ops.sc.rpc.grpc.callback.RpcCallBackResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RpcCallBackResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RpcCallBackResponse)
      com.ops.sc.rpc.grpc.callback.RpcCallBackResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ops.sc.rpc.grpc.callback.CallbackServiceProto.internal_static_RpcCallBackResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ops.sc.rpc.grpc.callback.CallbackServiceProto.internal_static_RpcCallBackResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ops.sc.rpc.grpc.callback.RpcCallBackResponse.class, com.ops.sc.rpc.grpc.callback.RpcCallBackResponse.Builder.class);
    }

    // Construct using com.ops.sc.rpc.grpc.callback.RpcCallBackResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      callBackType_ = 0;

      branchType_ = 0;

      tid_ = "";

      branchId_ = "";

      dataSource_ = "";

      callBackInterface_ = "";

      callbackMethod_ = "";

      params_ = com.google.protobuf.ByteString.EMPTY;

      requestId_ = "";

      registerResult_ = false;

      heartBeatResult_ = false;

      appName_ = "";

      resourceId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ops.sc.rpc.grpc.callback.CallbackServiceProto.internal_static_RpcCallBackResponse_descriptor;
    }

    @java.lang.Override
    public com.ops.sc.rpc.grpc.callback.RpcCallBackResponse getDefaultInstanceForType() {
      return com.ops.sc.rpc.grpc.callback.RpcCallBackResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.ops.sc.rpc.grpc.callback.RpcCallBackResponse build() {
      com.ops.sc.rpc.grpc.callback.RpcCallBackResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ops.sc.rpc.grpc.callback.RpcCallBackResponse buildPartial() {
      com.ops.sc.rpc.grpc.callback.RpcCallBackResponse result = new com.ops.sc.rpc.grpc.callback.RpcCallBackResponse(this);
      result.callBackType_ = callBackType_;
      result.branchType_ = branchType_;
      result.tid_ = tid_;
      result.branchId_ = branchId_;
      result.dataSource_ = dataSource_;
      result.callBackInterface_ = callBackInterface_;
      result.callbackMethod_ = callbackMethod_;
      result.params_ = params_;
      result.requestId_ = requestId_;
      result.registerResult_ = registerResult_;
      result.heartBeatResult_ = heartBeatResult_;
      result.appName_ = appName_;
      result.resourceId_ = resourceId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ops.sc.rpc.grpc.callback.RpcCallBackResponse) {
        return mergeFrom((com.ops.sc.rpc.grpc.callback.RpcCallBackResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ops.sc.rpc.grpc.callback.RpcCallBackResponse other) {
      if (other == com.ops.sc.rpc.grpc.callback.RpcCallBackResponse.getDefaultInstance()) return this;
      if (other.getCallBackType() != 0) {
        setCallBackType(other.getCallBackType());
      }
      if (other.getBranchType() != 0) {
        setBranchType(other.getBranchType());
      }
      if (!other.getTid().isEmpty()) {
        tid_ = other.tid_;
        onChanged();
      }
      if (!other.getBranchId().isEmpty()) {
        branchId_ = other.branchId_;
        onChanged();
      }
      if (!other.getDataSource().isEmpty()) {
        dataSource_ = other.dataSource_;
        onChanged();
      }
      if (!other.getCallBackInterface().isEmpty()) {
        callBackInterface_ = other.callBackInterface_;
        onChanged();
      }
      if (!other.getCallbackMethod().isEmpty()) {
        callbackMethod_ = other.callbackMethod_;
        onChanged();
      }
      if (other.getParams() != com.google.protobuf.ByteString.EMPTY) {
        setParams(other.getParams());
      }
      if (!other.getRequestId().isEmpty()) {
        requestId_ = other.requestId_;
        onChanged();
      }
      if (other.getRegisterResult() != false) {
        setRegisterResult(other.getRegisterResult());
      }
      if (other.getHeartBeatResult() != false) {
        setHeartBeatResult(other.getHeartBeatResult());
      }
      if (!other.getAppName().isEmpty()) {
        appName_ = other.appName_;
        onChanged();
      }
      if (!other.getResourceId().isEmpty()) {
        resourceId_ = other.resourceId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ops.sc.rpc.grpc.callback.RpcCallBackResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ops.sc.rpc.grpc.callback.RpcCallBackResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int callBackType_ ;
    /**
     * <pre>
     * commit还是rollBack
     * </pre>
     *
     * <code>int32 callBackType = 1;</code>
     */
    public int getCallBackType() {
      return callBackType_;
    }
    /**
     * <pre>
     * commit还是rollBack
     * </pre>
     *
     * <code>int32 callBackType = 1;</code>
     */
    public Builder setCallBackType(int value) {
      
      callBackType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * commit还是rollBack
     * </pre>
     *
     * <code>int32 callBackType = 1;</code>
     */
    public Builder clearCallBackType() {
      
      callBackType_ = 0;
      onChanged();
      return this;
    }

    private int branchType_ ;
    /**
     * <pre>
     * 分支类型
     * </pre>
     *
     * <code>int32 branchType = 2;</code>
     */
    public int getBranchType() {
      return branchType_;
    }
    /**
     * <pre>
     * 分支类型
     * </pre>
     *
     * <code>int32 branchType = 2;</code>
     */
    public Builder setBranchType(int value) {
      
      branchType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 分支类型
     * </pre>
     *
     * <code>int32 branchType = 2;</code>
     */
    public Builder clearBranchType() {
      
      branchType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object tid_ = "";
    /**
     * <pre>
     * 全局事务id
     * </pre>
     *
     * <code>string tid = 3;</code>
     */
    public java.lang.String getTid() {
      java.lang.Object ref = tid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 全局事务id
     * </pre>
     *
     * <code>string tid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTidBytes() {
      java.lang.Object ref = tid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 全局事务id
     * </pre>
     *
     * <code>string tid = 3;</code>
     */
    public Builder setTid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 全局事务id
     * </pre>
     *
     * <code>string tid = 3;</code>
     */
    public Builder clearTid() {
      
      tid_ = getDefaultInstance().getTid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 全局事务id
     * </pre>
     *
     * <code>string tid = 3;</code>
     */
    public Builder setTidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object branchId_ = "";
    /**
     * <pre>
     * 分支事务id
     * </pre>
     *
     * <code>string branchId = 4;</code>
     */
    public java.lang.String getBranchId() {
      java.lang.Object ref = branchId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        branchId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 分支事务id
     * </pre>
     *
     * <code>string branchId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBranchIdBytes() {
      java.lang.Object ref = branchId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        branchId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 分支事务id
     * </pre>
     *
     * <code>string branchId = 4;</code>
     */
    public Builder setBranchId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      branchId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 分支事务id
     * </pre>
     *
     * <code>string branchId = 4;</code>
     */
    public Builder clearBranchId() {
      
      branchId_ = getDefaultInstance().getBranchId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 分支事务id
     * </pre>
     *
     * <code>string branchId = 4;</code>
     */
    public Builder setBranchIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      branchId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dataSource_ = "";
    /**
     * <pre>
     *数据源，用于多数据源场景
     * </pre>
     *
     * <code>string dataSource = 5;</code>
     */
    public java.lang.String getDataSource() {
      java.lang.Object ref = dataSource_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataSource_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *数据源，用于多数据源场景
     * </pre>
     *
     * <code>string dataSource = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDataSourceBytes() {
      java.lang.Object ref = dataSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *数据源，用于多数据源场景
     * </pre>
     *
     * <code>string dataSource = 5;</code>
     */
    public Builder setDataSource(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataSource_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *数据源，用于多数据源场景
     * </pre>
     *
     * <code>string dataSource = 5;</code>
     */
    public Builder clearDataSource() {
      
      dataSource_ = getDefaultInstance().getDataSource();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *数据源，用于多数据源场景
     * </pre>
     *
     * <code>string dataSource = 5;</code>
     */
    public Builder setDataSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dataSource_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object callBackInterface_ = "";
    /**
     * <pre>
     *回调接口
     * </pre>
     *
     * <code>string callBackInterface = 6;</code>
     */
    public java.lang.String getCallBackInterface() {
      java.lang.Object ref = callBackInterface_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        callBackInterface_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *回调接口
     * </pre>
     *
     * <code>string callBackInterface = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCallBackInterfaceBytes() {
      java.lang.Object ref = callBackInterface_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        callBackInterface_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *回调接口
     * </pre>
     *
     * <code>string callBackInterface = 6;</code>
     */
    public Builder setCallBackInterface(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      callBackInterface_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *回调接口
     * </pre>
     *
     * <code>string callBackInterface = 6;</code>
     */
    public Builder clearCallBackInterface() {
      
      callBackInterface_ = getDefaultInstance().getCallBackInterface();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *回调接口
     * </pre>
     *
     * <code>string callBackInterface = 6;</code>
     */
    public Builder setCallBackInterfaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      callBackInterface_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object callbackMethod_ = "";
    /**
     * <pre>
     *回调方法
     * </pre>
     *
     * <code>string callbackMethod = 7;</code>
     */
    public java.lang.String getCallbackMethod() {
      java.lang.Object ref = callbackMethod_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        callbackMethod_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *回调方法
     * </pre>
     *
     * <code>string callbackMethod = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCallbackMethodBytes() {
      java.lang.Object ref = callbackMethod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        callbackMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *回调方法
     * </pre>
     *
     * <code>string callbackMethod = 7;</code>
     */
    public Builder setCallbackMethod(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      callbackMethod_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *回调方法
     * </pre>
     *
     * <code>string callbackMethod = 7;</code>
     */
    public Builder clearCallbackMethod() {
      
      callbackMethod_ = getDefaultInstance().getCallbackMethod();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *回调方法
     * </pre>
     *
     * <code>string callbackMethod = 7;</code>
     */
    public Builder setCallbackMethodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      callbackMethod_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString params_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *事务消息producerName以及TCC模式的参数
     * </pre>
     *
     * <code>bytes params = 8;</code>
     */
    public com.google.protobuf.ByteString getParams() {
      return params_;
    }
    /**
     * <pre>
     *事务消息producerName以及TCC模式的参数
     * </pre>
     *
     * <code>bytes params = 8;</code>
     */
    public Builder setParams(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      params_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *事务消息producerName以及TCC模式的参数
     * </pre>
     *
     * <code>bytes params = 8;</code>
     */
    public Builder clearParams() {
      
      params_ = getDefaultInstance().getParams();
      onChanged();
      return this;
    }

    private java.lang.Object requestId_ = "";
    /**
     * <pre>
     * 请求唯一标识
     * </pre>
     *
     * <code>string requestId = 9;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 请求唯一标识
     * </pre>
     *
     * <code>string requestId = 9;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 请求唯一标识
     * </pre>
     *
     * <code>string requestId = 9;</code>
     */
    public Builder setRequestId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求唯一标识
     * </pre>
     *
     * <code>string requestId = 9;</code>
     */
    public Builder clearRequestId() {
      
      requestId_ = getDefaultInstance().getRequestId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求唯一标识
     * </pre>
     *
     * <code>string requestId = 9;</code>
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestId_ = value;
      onChanged();
      return this;
    }

    private boolean registerResult_ ;
    /**
     * <pre>
     *注册成功标识
     * </pre>
     *
     * <code>bool registerResult = 10;</code>
     */
    public boolean getRegisterResult() {
      return registerResult_;
    }
    /**
     * <pre>
     *注册成功标识
     * </pre>
     *
     * <code>bool registerResult = 10;</code>
     */
    public Builder setRegisterResult(boolean value) {
      
      registerResult_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *注册成功标识
     * </pre>
     *
     * <code>bool registerResult = 10;</code>
     */
    public Builder clearRegisterResult() {
      
      registerResult_ = false;
      onChanged();
      return this;
    }

    private boolean heartBeatResult_ ;
    /**
     * <pre>
     *心跳返回
     * </pre>
     *
     * <code>bool heartBeatResult = 11;</code>
     */
    public boolean getHeartBeatResult() {
      return heartBeatResult_;
    }
    /**
     * <pre>
     *心跳返回
     * </pre>
     *
     * <code>bool heartBeatResult = 11;</code>
     */
    public Builder setHeartBeatResult(boolean value) {
      
      heartBeatResult_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *心跳返回
     * </pre>
     *
     * <code>bool heartBeatResult = 11;</code>
     */
    public Builder clearHeartBeatResult() {
      
      heartBeatResult_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object appName_ = "";
    /**
     * <pre>
     *客户端唯一appName标识
     * </pre>
     *
     * <code>string appName = 12;</code>
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *客户端唯一appName标识
     * </pre>
     *
     * <code>string appName = 12;</code>
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *客户端唯一appName标识
     * </pre>
     *
     * <code>string appName = 12;</code>
     */
    public Builder setAppName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *客户端唯一appName标识
     * </pre>
     *
     * <code>string appName = 12;</code>
     */
    public Builder clearAppName() {
      
      appName_ = getDefaultInstance().getAppName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *客户端唯一appName标识
     * </pre>
     *
     * <code>string appName = 12;</code>
     */
    public Builder setAppNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object resourceId_ = "";
    /**
     * <code>string resourceId = 13;</code>
     */
    public java.lang.String getResourceId() {
      java.lang.Object ref = resourceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string resourceId = 13;</code>
     */
    public com.google.protobuf.ByteString
        getResourceIdBytes() {
      java.lang.Object ref = resourceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string resourceId = 13;</code>
     */
    public Builder setResourceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resourceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string resourceId = 13;</code>
     */
    public Builder clearResourceId() {
      
      resourceId_ = getDefaultInstance().getResourceId();
      onChanged();
      return this;
    }
    /**
     * <code>string resourceId = 13;</code>
     */
    public Builder setResourceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resourceId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RpcCallBackResponse)
  }

  // @@protoc_insertion_point(class_scope:RpcCallBackResponse)
  private static final com.ops.sc.rpc.grpc.callback.RpcCallBackResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ops.sc.rpc.grpc.callback.RpcCallBackResponse();
  }

  public static com.ops.sc.rpc.grpc.callback.RpcCallBackResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RpcCallBackResponse>
      PARSER = new com.google.protobuf.AbstractParser<RpcCallBackResponse>() {
    @java.lang.Override
    public RpcCallBackResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RpcCallBackResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RpcCallBackResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RpcCallBackResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ops.sc.rpc.grpc.callback.RpcCallBackResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

